### ISSUE TITLE
Lav en mulighed for at linke direkte til en aktivitet - hvor man så kan tilmelde sig

### ISSUE THREAD

**Issue by nallic** [CodingPirates/forenings_medlemmer#101]
Hvis man ikke er logget på, skal man på aktiviteten guides til at få tilsendt et link (linket skal så direkte pege på aktiviteten igen - med mindre man har flere børn)

**Comment by rasmusselsmark** [comment]
Er implementeret med "offentlige aktiviteter", lukkes
