### ISSUE TITLE
Lad være med at fortælle om den har sendt email

### ISSUE THREAD

**Issue by lakridserne** [CodingPirates/forenings_medlemmer#102]
Ændr. teksten når man beder om adgang til familieside skal den ikke fortælle om den sender en email eller ej.

**Comment by nallic** [comment]
Skriv altid at der er sendt en email hvis man allerede er oprettet. Evt. for at mindske forbirring, sendes der er email hvor der står man ikke er oprettet i systemet.

Der er dog altid en fare ved at kunne sende emails via en webform - her kan man ikke medsende tekst, så det kan heldigvis ike bruges af spambots.

**Comment by lakridserne** [comment]
Solved
