### ISSUE TITLE
[BUG] Logud efterfulgt af logind resulterer i endnu et logud

### ISSUE THREAD

**Issue by dybber** [CodingPirates/forenings_medlemmer#1028]
## Beskriv fejlen overordnet

Jeg skulle teste at mit nye brugernavn/password virkede og for at gøre det lavede jeg et log ud efter fulgt af at jeg loggede ind igen. Det resulterede i at jeg blev viderestillet til https://members.codingpirates.dk/account/logout/ og blev logget ud igen.

## Genskab fejlen

Disse trin førte til fejlen:

1. Loggede ind
2. Klikkede på "Log ud" øverst til højre
4. Klikkede på "Log ind" øverst til højre
5. Udfyldte login formularen med mine oplysninger og klikkede "Log ind"
6. Jeg blev videre stillet til
7. https://members.codingpirates.dk/account/logout/ og logget ud igen

## Hvad skulle der være sket

Jeg skulle ikke være blevet logget ud lige efter jeg loggede ind

## Screenshots

Ingen

## Enheder

- OS: Mac OS X
- Browser: Firefox
- Smartphone/desktop: Desktop

**Comment by rasmusselsmark** [comment]
Muligvis relateret til https://github.com/CodingPirates/forenings_medlemmer/pull/968

**Comment by rasmusselsmark** [comment]
Done 🙂
