### ISSUE TITLE
[BUG] Deltager kan inviteres til aktivitet selvom de ikke er gamle nok, fordi de når at blive det inden aktiviteten begynder

### ISSUE THREAD

**Issue by HelloNicklas** [CodingPirates/forenings_medlemmer#1031]
## Beskriv fejlen overordnet

En beskrivelse af fejlen

Hvis en aktivitet f.eks er for 10-12 årige og man inviterer fra en venteliste, vil systemet også inviterer inviterer de 9-årige der fylder 10 år inden aktiviteten begynder. Forælderen kan dog ikke gennemføre tilmeldingen, før barnet er fyldt 10 år (hvilket kan risikerer at være efter tilmeldingen er lukket)

## Genskab fejlen

Disse trin førte til fejlen:

1. Oprettede aktivitet (BiK) der afholdes 13. april, med aldersgruppen 10-17 år
2. Inviterede børn fra ventelister i københavnsområdet
3. Valgte alle deltagere på hver enkel venteliste og trykkede "inviter valgte personer til en aktivitet"
4. Systemet inviterer alle børn på listen der er mellem 10 - 17 år, inklusiv børn der når at fylde 10 år inden aktiviteten.
5. Et eksempel kan være et barn der fylder 10 år den **11. april**, hvilket er efter tilmeldingsfristen der lukkede **5. april.**

## Hvad skulle der være sket

Enten skal systemet ikke inviterer børn til aktiviteten hvis de endnu ikke er fyldt 10 år den dato hvor invitationen blive sendt, eller også skal man kunne tilgå og gennemføre tilmeldingen hvis systemet kan se at barnet fylder 10 år inden aktivitetens begyndelse. Det vil jeg lade medlemssystems gruppen bestemme hvad der giver mest mening.

## Screenshots

ingen

## Enheder

- OS: Windows 11
- Browser: Opera One
- Smartphone/desktop: Desktop

**Comment by mhewel** [comment]
ActivitySignup.py: linje 116-119:
        if not (activity.min_age <= person.age_years() <= activity.max_age):
            return HttpResponse(
                f"Barnet skal være mellem {activity.min_age} og {activity.max_age} år gammel for at deltage. (Er fødselsdatoen udfyldt korrekt ?)"
            )

der skal sammenlignes med start dato for aktiviteten og barnets alder.
Hvis tilmelding er efter aktivitetens start skal der checkes om barnets alder denne dag er inden for aktivitets aldersgrænsen
