### ISSUE TITLE
[BUG] På Admin->E-mail side vises alle afdelinger og aktiviteter, ikke kun dem bruger har adgang til

### ISSUE THREAD

**Issue by rasmusselsmark** [CodingPirates/forenings_medlemmer#1052]
## Beskriv fejlen overordnet

Admin->Emails dropdown viser afdelinger/aktiviteter der ikke er relevante for mig

## Genskab fejlen

1. Åbn https://members.codingpirates.dk/admin/members/emailitem/
2. Vælg dropdown Afdeling eller Aktivitet

## Hvad skulle der være sket

Kun mine egne afdelinger/aktiviteter skulle vises i dropdown lister

## Screenshots

<img width="441" alt="image" src="https://github.com/CodingPirates/forenings_medlemmer/assets/3763552/61db5b7e-9548-481b-9dc4-aa3c94a1878e">

**Comment by mhewel** [comment]
Denne blev løst ifm release i sidste weekend
