### ISSUE TITLE
[BUG]Error 500 ved ændring af en addresse for en aktivitet der har for lav pris

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#1058]
## Beskriv fejlen overordnet
Forsøgte at sætte region for denne addresse:

http://members.codingpirates.dk/admin/members/address/571/change/

Det gav fejl 500.
Der er 1 aktivitet der  bruger denne adresse, og aktiviteten har en pris på 0 kr og er et forløb.

**Comment by mhewel** [comment]
Fejlhåndtering er lidt "skør".
Og mon ikke systemet burde acceptere gamle aktiviteter (der er afsluttet) med for lav pris ?

**Comment by mhewel** [comment]
Forslag:
i models/activity.py:
Nuværende:
 def clean(self):
        errors = {}
        min_amount = self.get_min_amount(self.activitytype.id)

        if self.price_in_dkk < min_amount:
            errors["price_in_dkk"] = (
                f"Prisen er for lav. Denne type aktivitet skal koste mindst {min_amount} kr."
            )

        if errors:
            raise ValidationError(errors)

nyt:

 def clean(self):
        if self.end_date > timezone.now():
            errors = {}
            min_amount = self.get_min_amount(self.activitytype.id)

            if self.price_in_dkk < min_amount:
                errors["price_in_dkk"] = (
                    f"Prisen er for lav. Denne type aktivitet skal koste mindst {min_amount} kr."
                )

            if errors:
                raise ValidationError(errors)

**Comment by mhewel** [comment]
Spørgsmålet er også: Hvorfor forsøger den at opdatere aktiviteten når address.region bliver opdateret ?

**Comment by rvpsolution** [comment]
Disse adresser har det samme problem:
590	Øster Alle 1, 2100 København
750	Solrød Center (Biblioteket) 4, 2680 Solrød
619	Jernbanegade 24 Stuen, 3600 Frederikssund
571	Farip Aqq. 8 , 3900 Nuuk
753	Borgerskolen, Alleen 7, 4180 Sorø
682	Spinderihallerne -1, 7100 Vejle
561	Spinderigade 11 Indgang K, 7100 Vejle
526	Spinderigade 11 Indgang K, 7100 Vejle
485	Skovvej 16, 8382 Hinnerup
768	balle torv
754	Vestre allé
737	Balle Torv Kælderen, 8600 Silkeborg
482	Bindslevs Plads 20, 8600 Silkeborg
776	Frederik Bajers Vej 7, 9000 Aalborg
580	Online 0, 9000 Aalborg
