### ISSUE TITLE
[BUG]Hvis man forsøger at oprette en aktivitet uden slutdato, så er der fejl 500

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#1070]
Hvis man opretter en aktivitet og ikke har sat en slutdato (og sikkert det samme m startdato), og gemmer, så er der fejl 500.

Start og slut datoer bør være mandatory, så der kommer en fornuftig fejl på skærmen med at feltet ikke er udfyldt.

**Comment by mhewel** [comment]
fejlen optræder her:

**Comment by mhewel** [comment]
vil det mon hjælpe at kalde super().clean som det første i clean ?

**Comment by rasmusselsmark** [comment]
Pull request er merged
