### ISSUE TITLE
[BUG] Ved invitation af visse personer fra ventelisten opleves denne fejl

### ISSUE THREAD

**Issue by lakridserne** [CodingPirates/forenings_medlemmer#1077]
## Beskriv fejlen overordnet
Jeg har fået indrapporteret en fejl fra Lyngby foreningen, hvor de ikke kunne invitere nummer 5, 4 og 3 på ventelisten til en aktivitet.

Fejlmeddelelsen er "TypeError("unsupported operand type(s) for +: NoneType and relativedelta")

**Comment by mhewel** [comment]
Har lige forsøgt at invitere de 3 personer til efterårsaktiviteten, og det virkede uden problemer. 
Vi parkerer lige denne bug for nu..

**Comment by rhl2401** [comment]
Det lader til, at fejlen opstår, hvis man vælger fx fra nr. 1 til X på ventelisten og en til flere er under den påkrævede alder for aktiviteten. I stedet for bare at springe personen over, opstår fejlen og ingen inviteres. 

Fejlbeskeden er dog ikke særlig sigende eller nøjagtig og inkluderer som bekendt en "(n/a)" mv. 

Måske man kunne bygge systemet således, at folk, der ikke er gamle nok til aktiviteten, blot ikke inviteres og alle andre så gør?

**Comment by mhewel** [comment]
tak @rhl2401 - jeg ser på det.
Vi lavede en ændring sidste år så man kan vælge personer og sende invitationer ud. For hver person bliver der checket om personen er inden for aldersgrænsen, allerede er blevet inviteret, allerede deltager etc.
Således at man ikke bliver inviteret hvis man ikke har rette alder (for ung/for gammel), allerede er inviteret eller allerede er på aktiviteten. 
Men tak for observationen, jeg prøver lige forskellige ting af på baggrund af din beskrivelse

**Comment by mhewel** [comment]
Ah - jeg er nu istand til at reproducere fejlen !

**Comment by mhewel** [comment]
@rhl2401 - der er 2 personer på jeres venteliste der har alderen 0 år , det skyldes at deres fødselsdato ikke er sat.
Dette er desværre årsagen til fejlen, og som nu kan rettes.
Det vil være en god ide at skrive til de 2 familier/personer at de skal sætte fødselsdato for deres barn, ellers bliver de aldrig inviteret !

**Comment by mhewel** [comment]
Så er PR 1088 (https://github.com/CodingPirates/forenings_medlemmer/pull/1088) klar

**Comment by rhl2401** [comment]
Arh, det giver mening. Så er det ikke noget problem, hvis folk bare ikke er gamle nok. Alderen må bare ikke være 0. 

Jeg har lige testet og kan konstatere, at det virker, hvis folk bare ikke er 0 år. 

Tak for hjælpen!
