### ISSUE TITLE
Tilføj automatisk region til union udfra adresse model

### ISSUE THREAD

**Issue by Rotendahl** [CodingPirates/forenings_medlemmer#111]
Problemet er primært de linjer her 
https://github.com/CodingPirates/forenings_medlemmer/blob/4e364bd8d98179ccf167ca0f35476073a2bbacfb/members/models/union.py#L26-L27

Nu hvor alle foreninger har en [adresse](https://github.com/CodingPirates/forenings_medlemmer/blob/master/members/models/address.py) forbundet burde vi splitte det over til at bruge den. Det ville også gøre at kan opdatere [afdelingssiden](https://members.codingpirates.dk/departments). 

Vi henter adresse data fra dawa, det er muligt at få en region med fra dem. Det er de 5 danske regioner vi kan bruge så feks. "Region Sjælland"

1.  Fjern regionsfeltet fra union.py.
2. Opdater Adddress factory til at vælge en tilfældig region. 
2. Gør sådan at man kan se region på adresse admin. 
4. Gør sådan at man stadig kan filtrere foreninger ud fra regioner i admin interfacer. 
5. Gør sådan at `/departments` virker med det nye setup.

**Comment by Rotendahl** [comment]
Brug commit 8cca7ed5b6a901624fa60b6b65de8a799d6580da

**Comment by Rotendahl** [comment]
Den her kan løses ved at bruge "regionsnavn" som kommer i dawa svaret. 
Så har vi 5 regioner

**Comment by JondareHM** [comment]
Hvad mener du med at man stadig skal kunne filtrere ud fra region på admin siderne? så vidt jeg kan se er der ikke et eneste sted hvor det er tilfældet. Mener du bare at jeg skal implementere det? For kan se hvordan det måske er praktisk i Union_admin, og måske endda department_admin selvom man der allerede kan filtrere efter forening

**Comment by Rotendahl** [comment]
Ord, der skulle ikke så stadig. Det er på admin listen jeg mener :)

**Comment by JondareHM** [comment]
Hvilken admin liste? Altså inde på union_admin?

**Comment by Rotendahl** [comment]
Jeps, sådan at man kan filtere listen her efter region. 
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/3578071/74157546-bfdbca80-4c18-11ea-977f-0997058e62cb.png">
Det er bare en linje der skal tilføjes på unionAdmin

**Comment by JondareHM** [comment]
Eh, skal vel også lige definere det her nye region filter, men burde heller ikke være svært
