### ISSUE TITLE
Opret dataudtræks endpoint

### ISSUE THREAD

**Issue by nallic** [CodingPirates/forenings_medlemmer#121]
vi skal have et /api/anonymized/* endpoint med forskellige kald til at hente data ud af systemet, i filtreret tilstand.

Evt. skal der både være en option for csv og json.

Et script kan hente disse data og opbygge en fornuftig test database, med aktuelle data fra det rigtige system, uden der er navne, adresser, fødselsdage, betalingsoplysninger, eller andet, der regnes for hemmeligt.

Evt kan tidsstempler begrænset til timer eller måneder, hvor det er relevant, for yderligere at skjule de rigtige data, men gør det muligt at bruge data til test fornuftigt.

**Comment by jenrik** [comment]
Det skal overvejes om det bedre kan betale sig at genere tilfældig data end at forsøge at anonymisere eksisterende data

**Comment by lakridserne** [comment]
Pointen med at have anonymiserede data var at vi kunne bruge det til statistik samtidig med. Ofte får vi forespørgsler som f.eks. hvor mange står der på venteliste på denne her afdeling? Med anonymiserede data kan man gå ind og se at ting som antallet på venteliste er stadig korrekt - de ting der bare ikke må komme ud kommer ikke ud.

**Comment by jenrik** [comment]
Til test formål kunne det måske være bedre med noget genere data for at kunne nå nogle flere edge cases. Måske man kunne kombinere generede data og anonymiserede data?

**Comment by dybber** [comment]
Jeg har arbejdet lidt i den retning ifbm. at jeg har forsøgt at lave et dashboard hvor man kan få overblik over medlemsdatabasen via forskellige visualiseringer. Pt. har jeg kun brugt den anonymiserede database @lakridserne har givet mig.

https://github.com/CodingPirates/cp-dataviz

Jeg laver en tabel hvor tid er på måneds-niveau, navne osv. er forsvundet, fødselsdag omregnet til alder og børn med lignende karakteristik (alder, køn, post nummer, afdeling, antal sæsoner tilmeldt) er grupperet under et. Det er ofte kun 1 barn per gruppe, så helt anonymt er det nok ikke, men måske er det anderledes på den ikke-randomiserede database.

**Comment by lakridserne** [comment]
Denne skal vi måske overveje om det er nu - og om vi hellere skal kigge på GraphQL.
