### ISSUE TITLE
C/O adresser

### ISSUE THREAD

**Issue by lakridserne** [CodingPirates/forenings_medlemmer#124]
Vi understøtter ikke at man kan bruge en C/O adresse. Det bør vi gøre.

**Comment by jenrik** [comment]
Hvad forskel gør det for os om en person har en almen address eller en C/O adresse?

**Comment by lakridserne** [comment]
Det var ment til adresser til foreninger - nu er det af gode grunde yderst sjældent vi rent faktisk sender noget post til foreninger, men i det tilfælde man skulle det så er det fint at have.

**Comment by DSDeniso** [comment]
Jeg vil lige bemærke at jeg lige er flyttet ud og har en C/O-adresse :-)

**Comment by jenrik** [comment]
Skal vi lave det sådan at der er et dedikerede felt til C/O adresse? eller skal vi bare lave en tjek boks det indikere om det er en almen adresse eller en C/O adresse vi har opbevaret?

**Comment by rasmusselsmark** [comment]
Lukkes, da vi vurderer i udviklergruppen ikke mener dette er stort nok problem til at skulle prioriteres
