### ISSUE TITLE
forkert URL kodning i Department modellen

### ISSUE THREAD

**Issue by jenrik** [CodingPirates/forenings_medlemmer#127]
I funktion get_long_lat i Department modellen generes en URL via sammenføjelse af en del af en URL og adressen uden at kode alle relevante karakterer i adressen.

Jeg forslår at erstatte følgende i get_long_lat:
`req = 'https://dawa.aws.dk/datavask/adresser?betegnelse=' + self.address_with_zip().replace(" ", "%20")`
med:
`req = 'https://dawa.aws.dk/datavask/adresser?betegnelse=' + quote_plus(self.address_with_zip())`
hvor quote_plus funktion importere fra `urllib.parse`

Hvis for eksempel at streetname sættes til `&junk=` fejler get_long_lat

**Comment by Rotendahl** [comment]
De eneste adresser der bliver slået op der er dem på afdelingerne. 
Så det kræver aktivt at en går ind i admin interface og ændrer deres vejnavn til &junk

**Comment by jenrik** [comment]
Alt med et `&` vil give en fejl tror jeg nok.
Og hvorfor ikke bare gøre det rigtigt?

**Comment by Rotendahl** [comment]
Jeg har lige kørt det og det virker som det skal, så vi kan fint merge det ind. 

Er der nogle vejnavne hvor `&` indgår? :)

**Comment by jenrik** [comment]
Jeg har ikke nogen ide om om der er nogen vejnavne der indeholder `&`, men det ville ikke overraske mig

**Comment by jenrik** [comment]
Skal jeg bare committe det til develop branchen så?

**Comment by Rotendahl** [comment]
Lad os lige fikse det med latitude `&` longtitude samtidigt. ;)

**Comment by Rotendahl** [comment]
Vil du gøre det i den her branch? 
Jeg kan fint gøre det hvis du ikke har tid 😄

**Comment by jenrik** [comment]
Jeg committer det til develop branchen på CodingPirates repository
