### ISSUE TITLE
from_address i EmailTemplate bliver ikke brugt

### ISSUE THREAD

**Issue by jenrik** [CodingPirates/forenings_medlemmer#128]
`from_address` feltet i `EmailTemplate` modellen bliver ikke brugt, i stedet bruges `SITE_CONTACT` fra settings.
Jeg forslåer at vi enten fjerner `from_address`, eller laver det om så `SITE_CONTACT` er en fallback til hvis `from_address` ikke er sat

**Comment by Rotendahl** [comment]
Bliver fikset i den nye version
