### ISSUE TITLE
Masseinvitationer inviterer selvom deltager er for ung eller gammel

### ISSUE THREAD

**Issue by lakridserne** [CodingPirates/forenings_medlemmer#140]
Masseinvitationer kigger ikke på alder.

**Comment by dybber** [comment]
Er den her ikke fikset?

**Comment by rasmusselsmark** [comment]
Ifølge @lakridserne og @mhewel er denne rettet (dog kigges der på barnets nuværende alder, og ikke når aktiviteten starter, men det er andet issue)
