### ISSUE TITLE
Der skal sendes email kvitteringer for alle vigtige hændelser

### ISSUE THREAD

**Issue by nallic** [CodingPirates/forenings_medlemmer#149]
Nu sendes der en "du er tilmeldt" kvittering, når man både er tilmeldt samt har betalt.

Der bør sendes:

Tilmeldt
Betaling modtaget
Manglende betaling (rykker)

**Comment by rasmusselsmark** [comment]
Vi lukker den for nu, rykker dækkes af #97, øvrige punkter er mindre vigtige
