### ISSUE TITLE
UX: personer skal kunne tilmelde sig, uden aktivitet.

### ISSUE THREAD

**Issue by nallic** [CodingPirates/forenings_medlemmer#151]
Der skal tænkes over at forældre ikke ved en fejl skal tilmelde deres børn som medlemmer, hvis de allerede er med på en aktivitet.

Der skal heller ikke kunne misforstås at børn, ikke kommer med på en aktivitet, hvis de bliver medlemmer.

Børn og voksne, kan godt blive medlemmer, men børn vil typisk blive det i forbindelse med tilmelding til en aktivitet.

**Comment by rasmusselsmark** [comment]
Er forsøgt implementeret med f.eks. foreningsmedlemsskaber, vi lukker dette issue
