### ISSUE TITLE
Implementering af favicon.ico

### ISSUE THREAD

**Issue by benj5378** [CodingPirates/forenings_medlemmer#156]
Tilføje et favicon.ico

**Comment by Rotendahl** [comment]
Fixed in #160

**Comment by sulfo** [comment]
@Rotendahl: Når mit pull request lander i master skulle issuet gerne selv blive lukket, fordi jeg har skrevet `fixes #160` i pull requested.
Læs mere[ her omkring GitHubs featuren](https://github.com/blog/1506-closing-issues-via-pull-requests)
