### ISSUE TITLE
Dockerization af dev miljø

### ISSUE THREAD

**Issue by lronhoj** [CodingPirates/forenings_medlemmer#168]
Issue så vi kan diskutere docker setup.

**Comment by lronhoj** [comment]
Har i prøvet docker setuppet af?

**Comment by dybber** [comment]
Er den her ikke fikset?

**Comment by Rotendahl** [comment]
Jeps, der er en `docker-compose` fil, og en guide til hvordan det sætte op her. 
https://github.com/CodingPirates/forenings_medlemmer/blob/master/CONTRIB.md
