### ISSUE TITLE
Flyt email templates ud af DB og ned i .html filer.

### ISSUE THREAD

**Issue by nallic** [CodingPirates/forenings_medlemmer#188]
Nu er det alt for besværligt at arbejde med templates. Man skal teste lokalt med en template i dev database og den skal efterfølgende op på produktion. 

Et commit der bruger en ny template, skal indeholde denne template og det gøres nemmest hvis de ligger som filer.

I praksis er der ingen der opdaterer templates live.

I samme omgang bør templates pudses af. Deres ordlyd er nok ikke længere tidsvarende.

**Comment by lakridserne** [comment]
Skal vi ikke putte de nuværende templates op på Slack og få folk til at hjælpe med at pudse dem af? Så er vi da mere sikre på at alle er enige med ordlyden (ved godt det ikke bliver alle der er enige i praksis, men vi kan jo godt forsøge).

**Comment by lakridserne** [comment]
Samtidig med vi evt. smider en lille notits i næste nyhedsbrev om, at man kan være med til det.

**Comment by rasmusselsmark** [comment]
Ikke vigtig, lukkes (blev vi enige om på udviklergruppemøde i dag 🙂 )
