### ISSUE TITLE
Forkert besked ved invitation af allerede inviteret

### ISSUE THREAD

**Issue by tbfangel** [CodingPirates/forenings_medlemmer#193]
Når man inviterer en række personer til en aktivitet og nogen allerede er inviteret kommer en besked i toppen om dette. Listen af navne der vises er dog dem der blev inviteret, ikke dem der allerede var inviteret. 
Screenshottet herunder viser beskeden hvor 1 ud af de 24 valgte allerede var inviteret:
<img width="1411" alt="screen shot 2018-08-21 at 21 42 01" src="https://user-images.githubusercontent.com/6099592/44425484-47003300-a58c-11e8-93a8-a184f6296664.png">

**Comment by rasmusselsmark** [comment]
Der skal vises:
- Hvem der allerede var inviteret
- Udenfor aldersgruppe

**Comment by mhewel** [comment]
måske burde der også være check for om personen allerede deltager.

**Comment by mhewel** [comment]
Logikken er ændret tidligere i år, så der listes dem der er inviteret, dem der ikke er gamle nok, dem der allerede deltager, dem der er for gamle
