### ISSUE TITLE
Invitation af børn uden for ældersgrænser, skal give mere markant fejl

### ISSUE THREAD

**Issue by dybber** [CodingPirates/forenings_medlemmer#220]
Hvis man inviterer børn til en aktivitet hvor de er uden for aldersgrænsen, så bliver de bare ignoreret. I stedet bør man få en fejl tilbage, så man er klar over at børnene ikke er blevet inviteret, og at det er på grund af aldersgrænsen.

**Comment by dybber** [comment]
Tilføjelse: Jeg inviterer altid ved at søge personen frem først inde i "personer" kryds af og sige "Inviter alle valgte til en aktivitet", også hvis det kun er én person jeg inviterer.

Det er formentlig primært et problem der opstår når man får en frivillig der vil have børn med, men som egentlig er lidt for ung til resten af afdelingen.

**Comment by lakridserne** [comment]
Denne er løst - den sortere personer fra hvis de falder udenfor aldersgrænsen.
