### ISSUE TITLE
Der skal være en hold/workshopsleder rolle/gruppe

### ISSUE THREAD

**Issue by sunenilausen** [CodingPirates/forenings_medlemmer#232]
Denne person skal kunne gøre ting omkring aktiviteter og hold.

**Comment by lakridserne** [comment]
På udviklermøde d. 17. april, er vi blevet enige om, at lukke denne, og kigge nærmere ind i noget i denne stil når vi har frivillige i systemet, samt når vi har #877 implementeret / er i gang med at implementere den.
