### ISSUE TITLE
Afdelingskaptajnen skal kunne se børneattester for sine frivillige

### ISSUE THREAD

**Issue by sunenilausen** [CodingPirates/forenings_medlemmer#239]
Design en process for SEK og systemet der gør børneattester nemmere

**Comment by JakobLibak** [comment]
@lakridserne uploader diagram med workflow for håndtering af børneattester.

**Comment by lakridserne** [comment]
[_Blank UML.pdf](https://github.com/CodingPirates/forenings_medlemmer/files/5484329/_Blank.UML.pdf)

**Comment by lakridserne** [comment]
Spørg hvis der er spørgsmål

**Comment by JakobLibak** [comment]
@thejomas Se pdf dokument her for forslag til håndtering af frivillige + børneattester.

**Comment by lakridserne** [comment]
Denne lukkes med henvisning til #110
