### ISSUE TITLE
Som afdelingskaptajn kan man lave standardopsætning for sæsoner.

### ISSUE THREAD

**Issue by sunenilausen** [CodingPirates/forenings_medlemmer#250]
Så det kan genbruges fra sæson til sæson og ikke skal skrives igen.

**Comment by lakridserne** [comment]
På udviklermøde d. 17. april er vi blevet enige om, at lukke denne ticket, da man kan kopiere en aktivitet. På sigt vil der muligvis blive kigget på brugervenlighed, men det er ikke relevant pt. da der er andre tickets der er prioriteret højere.
