### ISSUE TITLE
Det skal være nemmere at afkrydse om deltagere har deltaget/fremmødt

### ISSUE THREAD

**Issue by sunenilausen** [CodingPirates/forenings_medlemmer#251]
Det er pt. muligt men kræver en del kliks i et ikke særligt intuitivt admin panel

**Comment by lakridserne** [comment]
Det er faktisk ikke muligt pt., det er blot muligt i mit separate system. Men koden kan flyttes over ret nemt så det er muligt, og så kan vi gøre det pænere og mere intuitivt.

**Comment by lakridserne** [comment]
På udviklermøde d. 17. april er vi blevet enige om, at lukke denne ticket da vi har #877 der beskriver denne issue.
