### ISSUE TITLE
Det skal være mulig for afdelingskaptajn at kunne hjælpe forældre med opdatring af bruger og ændringer på aktivitets forhold.

### ISSUE THREAD

**Issue by sunenilausen** [CodingPirates/forenings_medlemmer#254]

**Comment by lakridserne** [comment]
På udviklermøde d. 17. april er vi blevet enige om, at lukke denne ticket da det anses for relativt få gange denne feature bliver brugt, set i forhold til den kompleksistet det vil tilføje til systemet.

Dette vil nemlig kræve flg.
- Man skal som afdelingskaptjan kunne impersonate en bruger / familie
- Kun relevant info skal være synlig fo afdelingskaptajnen. Dvs. f.eks. skal fysisk postadresse ikke være synligt
- Alle actions skal trackes, så vi ved hvem der har været hvor, og hvad de har lavet.
