### ISSUE TITLE
Opsætning af Faker til testmiljø

### ISSUE THREAD

**Issue by sunenilausen** [CodingPirates/forenings_medlemmer#256]
https://github.com/joke2k/faker

**Comment by dybber** [comment]
Jeg er gået i gang. Progress kan følges her: https://github.com/dybber/forenings_medlemmer/tree/feature/faker_factories

**Comment by Rotendahl** [comment]
Resolved in #277

**Comment by dybber** [comment]
Arh, den er ikke helt i mål. Mangler stadig for et par modeller

**Comment by Rotendahl** [comment]
Cool, var lige hurtig nok til at lukke den.
Du kan evt. kombinere den med #284, så du f.eks trækker live data til afdelinger og foreninger.

**Comment by dybber** [comment]
Sådan at den ikke autogenerer afdelingerne? Det tænker jeg lyder dumt, vi skal vel tjekke for random data at det virker, sådan at det også virker for fremtidige afdelinger

**Comment by Rotendahl** [comment]
Det kan der være noget om, vi forsætter med random data.

**Comment by dybber** [comment]
Idéelt set burde hver test bliver kørt 100 gange med forskelligt random data hver gang, Quickcheck-style, men jeg har ikke lige kigget på om Python har tilsvarende biblioteker.

**Comment by lakridserne** [comment]
På udviklermøde d. 17. april er vi blevet enige om, at lukke denne, da vi bruger Faker. Hvis vi senere finder tabeller der ikke kan testes pga. manglende faker på disse, kan vi tilføje tabellerne når vi finder ud af det.
