### ISSUE TITLE
Ventelister skal være mere overskuelig

### ISSUE THREAD

**Issue by sunenilausen** [CodingPirates/forenings_medlemmer#263]
Det vil stadig være dejligt at have et estimat på ventetiden samt en forklaring på invitationsrækkefølgen.

**Comment by Rotendahl** [comment]
<img width="1590" alt="Screenshot 2019-10-01 at 14 33 41" src="https://user-images.githubusercontent.com/3578071/65962615-5d4c1400-e459-11e9-8221-1f510c8ed7a1.png">

Gør sådan at den bare viser pladser
