### ISSUE TITLE
Gør sådan at bestyrelsesposter peger på user/person i union

### ISSUE THREAD

**Issue by Rotendahl** [CodingPirates/forenings_medlemmer#370]
Foreningsmodellen skal have en bedre måde at håndtere hvem der har hvilke poster. 
https://github.com/CodingPirates/forenings_medlemmer/blob/master/members/models/union.py

Lige nu er det bare tekstfelter til de forskellige poster. I stedet burde det være: 
1. (Chairman, second_chair, cashier) : skal alle være foreign keys. 
2. board_members skal være many to many. 
3. Lav en migration. 
4. Der skal laves en nem måde at sætte hvem der kan være formand i en dropdown. Lav evt. et queryset hvor alle voksne medlemmer af foreningen vises.

**Comment by JondareHM** [comment]
Før jeg går i gang med den her: Chairman osv. skal stadig bare være foreign keys, ikke manytomany ligesom afdelings leder?

**Comment by Rotendahl** [comment]
Jeps, de er juridiske poster som kun kan besides af en person og de skal være udfyldt :)

**Comment by Rotendahl** [comment]
Jeg er faktisk i tvivl om sekretær og formand er juridiske poster på samme måde som en formand og kasserer. 

Hør evt. Michael om de også skal være der

**Comment by JondareHM** [comment]
Ok. chairman_email osv, skal jeg bare tage det fra deres Person når vi nu alligevel kobler det sammen, eller er der en vigtig grund til stadig at have dem som et separat tekst felt?

**Comment by Rotendahl** [comment]
God spørgsmål

Lav det evt. sådan at den hedder “union_email” så skriver man til den hvis man vil skrive til foreningen og så tager man chaimain.email hvis man vil skriv til formanden.

**Comment by JondareHM** [comment]
Der er faktisk allerede en union_email defineret, så der behøver jeg ikke gøre noget :) Men jeg laver chairman_email og de andre om til at tage fra person så

**Comment by Rotendahl** [comment]
Super!

**Comment by JondareHM** [comment]
I modsætning til afdelingsledere så er foreningsledere og second chairs osv osv ikke nødvendigvis admins, er de?

**Comment by lakridserne** [comment]
Både afdelingsledere og bestyrelsesmedlemmer kan være admins men er det ikke nødvendigvis. Det afhænger af den lokale organisering.

**Comment by JondareHM** [comment]
Ok, så jeg sætter det ikke som et af filtrene til hvem man kan vælge

**Comment by lakridserne** [comment]
Formand og kasserer skal besiddes - næstformand og sekretær kan være - ligesom menige kan være. Samme med suppleanter (og vi bør i virkeligheden tilføje et separat felt til det).

Når du siger filtrene hvor mener du så? I admin user information?

**Comment by JondareHM** [comment]
Jeg kan allerede på modellen bruge limit_choices_to til foreksempel at sige at man kan kun vælge admins (is_staff) til den plads, og det så også kun er dem som kommer frem inde i admin dropdownen.

Når det ikke er nødvendigt sidder jeg så og fifler med kun at vise voksne medlemmer af foreningen

**Comment by lakridserne** [comment]
Altså du kan fint sætte et filter ind. Mange foreninger har jo bestyrelsesmedlemmer som admins.

Den med voksne medlemmer forstår jeg ikke helt hvorfor den skal blandes ind i denne her specifikt.

**Comment by JondareHM** [comment]
Det er for at gøre dropdowsne til valg af bestyrelsesmedlemmerne mere overskuelige, så det ikke er en liste over vitterligt samtlige medlemmer i Coding Pirates

**Comment by lakridserne** [comment]
Børn kan også godt være bestyrelsesmedlemmer. Det er nok bedre at bruge et raw_id_field ligesom f.eks. på personen når man skal vælge familie.
