### ISSUE TITLE
Send mail med opdatering af oplysninger og fjern ventelister

### ISSUE THREAD

**Issue by Rotendahl** [CodingPirates/forenings_medlemmer#385]
Vi skal have en bedre måde at resette venteliste og holde oplysinger opdateret.

**Comment by JakobLibak** [comment]
Forslag:
Tilføj to felter under afdelinger:
- Ny sektion under `admin/members/department/x/change/`: Ventelister
- Hjælpetekst: *Angiv om din afdeling arbejder med ventelister. Hvis ventelister er aktiveret vil forældre kunne skrive deres børn op uden for normal tilmelding, og I kan senere sende invitationer til børn på ventelisten. Hvis du angiver at opskrivninger kan udløbe vil børn automatisk blive fjernet fra ventelisten, når tidsfristen siden deres opskrivning er overskedet.*
- Nye felter til `members_department`
    - `isWaitlistActive` [bool]. Default value: TRUE. Vises som tekst *[ ] Venteliste aktiv*
    - `isExpiringWaitlist` [bool]. Vises som tekst *[ ] Ventelisteopskrivninger kan udløbe* 
    - `waitlist_expires_after` [int]. Vises som tekst *Dage fra opskrivning til udløb*
 - Under `/department_signup` og listen over opskrivninger skal der være en [Forny] knap for hver opskrivning, hvor man kan bekræfte sin opskrivning. Samme liste skal vise hvornår hver enkelt opskrivning udløber ([dato] eller *Aldrig*)
 - Cron-job skal dagligt slette opskrivninger, der er udløbet.

**Comment by lakridserne** [comment]
På udviklermøde d. 17. april er vi blevet enige om, at lukke denne da denne er implementeret.
