### ISSUE TITLE
Opdater styling på "reset password" side

### ISSUE THREAD

**Issue by Rotendahl** [CodingPirates/forenings_medlemmer#386]
![Screenshot 2020-01-11 at 11 57 42](https://user-images.githubusercontent.com/3578071/72203275-aef93700-3469-11ea-8263-8a1b8c45a53d.png)

Sørg for at email felt er i midten, og formen er lidt pænere.

**Comment by Un10ck3d** [comment]
Den her er vel færdig. Eller skal andet ændres?

**Comment by mhewel** [comment]
Siden ser nu sådan her ud:
![Screenshot_2024-07-04_19-44-44](https://github.com/user-attachments/assets/fc1e7c45-67d8-4fd8-b104-90d239ec39dd)
Det er klart bedre end det tidligere , jeg vil foreslå at vi lukke denne
