### ISSUE TITLE
[BUG] Password reset

### ISSUE THREAD

**Issue by Rotendahl** [CodingPirates/forenings_medlemmer#390]
**Beskriv fejlen overordnet**
Password reset virker ikke optimalt. 
SEK får en del support henvendelser på det. 

Fejlen skyldes nok både noget usability med forskellen på "Glemt password, opret password". 
Samtidigt så kunne siderne styles lidt bedre og vi kan lave tests til det. 

**Genskab fejlen**
Disse trin førte til fejlen:
1. Trykker på  login i menu bare '...'
2. Klikkede på Glemt adgangskode/opret adgangskode '....'
4. Jeg fik ikke en mail 

**Hvad skulle der være sket**
Jeg skulle have fået en mail og kun have haft en mulighed med opret/glemt adgangskode

**Comment by JondareHM** [comment]
Ser ud til at være fikset, selv hvis man bare trykker direkte på login så kommer man nu ind på den rigtige login side, med kun Glemt Password knap
