### ISSUE TITLE
[BUG] Hvis man trykker på et link til en afdeling, så åbner det en side i siden, i stedet for bare at skifte til afdelingens side

### ISSUE THREAD

**Issue by JondareHM** [CodingPirates/forenings_medlemmer#419]
![2020-01-20_15h57_09](https://user-images.githubusercontent.com/17178122/72737136-46176a80-3b9f-11ea-975c-39e51fbaf159.png)

**Comment by Rotendahl** [comment]
Det kan løses ved at tilføje en target="_blank" på `<a>` tagget.
