### ISSUE TITLE
Åbne events bliver stående selvom man er tilmeldt dem

### ISSUE THREAD

**Issue by nallic** [CodingPirates/forenings_medlemmer#43]
vær opmærksom på at et åbent event vises for evt. flere børn. Det burde forsvinde for de event+barn, hvor de allerede er tilmeldt.

Dog ændrer tilmeld knappen funktion, hvis man er tilmeldt. Idet den i stedet viser aktivitet info + hold liste.

**Comment by lakridserne** [comment]
Denne bug er fikset. Denne issue blev ikke lukket ved en fejl.
