### ISSUE TITLE
[Feature] Søgefelt på /departments/ siden

### ISSUE THREAD

**Issue by JondareHM** [CodingPirates/forenings_medlemmer#437]
Et simpelt søgefelt på /departments/, så man nemt kan finde sin afdeling derinde

**Comment by mhewel** [comment]
Der er lavet søgefelt på https://members.codingpirates.dk/admin/members/department/, der søger i flg felter under department/afdeling:
navn
foreningsnavn
adresse: streetname, housenumber, placename, zipcode, city
description/beskrivelse
