### ISSUE TITLE
[Feature] Afdelings email og link til afdelings hjemmeside inde på venteliste oversigten

### ISSUE THREAD

**Issue by JondareHM** [CodingPirates/forenings_medlemmer#438]
![2020-01-28_16h10_39](https://user-images.githubusercontent.com/17178122/73276808-8c954680-41e9-11ea-9fa5-4a9b8f9d7b64.png)

Lav navnet om til et link, og evt. placer emailen under navnet, ser ud til at være rigeligt med plads.

**Comment by benj5378** [comment]
Fixes i PR #334
