### ISSUE TITLE
Workshops på aktivitet

### ISSUE THREAD

**Issue by benj5378** [CodingPirates/forenings_medlemmer#440]
**Overordnet beskrivelse af funktionen**
Der skal kunne oprettes workshops til en aktivitet, evt. med begrænset antal pladser, så brugere kan tilmelde sig en bestemt workshop og afd.led. se antal tilmeldte workshop

**User story**
1. Tilmelder aktivitet
2. Vælg workshop

(har allerede tilmeldt sig aktivitet)
1. Åbner den tilmeldte aktivitet
2. Vælger/ændrer workshop

**Comment by lakridserne** [comment]
På udviklermøde d. 17. april er vi blevet enige om, at lukke denne med henvisning til at det er implementeret i prototype til #877
