### ISSUE TITLE
Lav "inviter til aktivitet" handling i PersonAdmin

### ISSUE THREAD

**Issue by nallic** [CodingPirates/forenings_medlemmer#45]
http://agiliq.com/blog/2014/08/passing-parameters-to-django-admin-action/

**Comment by nallic** [comment]
Pas rigtigt meget på det her ikke bliver for nemt at kludre med. Der skal være en "du sender nu til XXX personer trippel advarsel"

**Comment by Rotendahl** [comment]
Den er lavet
