### ISSUE TITLE
Refactor activityparticipant-testen

### ISSUE THREAD

**Issue by benj5378** [CodingPirates/forenings_medlemmer#456]
`members/tests/test_model_activityparticipant.py` bør omkskrives, da der er kode, der reelt ikke bliver brugt til noget.

Testen skal også være langt mere omfattende. Fx teste anciennitet

**Comment by lakridserne** [comment]
Generelt set er vores tests noget der er tilføjet for nyligt - og derfor tilføjer vi mere coverage løbende. Det er bl.a. også derfor vi har en coverage report når man tilføjer et pull request.

Hvad er det for noget kode du mener der ikke bliver brugt?
