### ISSUE TITLE
[BUG]Export CSV har ikke alle kolonner med f.x. ikke køn

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#469]
Når man exporterer personer, er der i flg værdier vist:
Navn, type, køn, familie, alder, postnummer, tilføjet, noter
Men i CSV fil der kan exporteres er der:
Navn, alder, Opskrevet, Tlf (barn), email (barn), tlf (forælder), email (familie), postnummber
Jeg savner bl.a. køn

Under Admin, vælg Personer, filtrer på en aktivitet.
Se data på skærmen, vælg en eller flere personer, og derefter "Eksporter CSV"

Jeg ville gerne have en export af data af de deltagere jeg har på en aktivitet, kunne se at Køn ikke var med. I et andet view er der desuden også angive Foto tilladelse - det kunne også være godt at få exporteret til v´CSV

**Comment by lakridserne** [comment]
Det kunne være fint at få flere kolonner med. Vi skal dog holde os til ting folk i forvejen har adgang til - dvs. adresser skal for eksempel ikke med.

Mht. fototilladelse kan det blive en udfordring at få med medmindre man før man eksporterer skal vælge hvilken aktivitet man evt. vil eksportere (ligesom man vælger når man inviterer).

**Comment by mhewel** [comment]
klart, vi skal selvfølgelig tænke os om, men fra min side: hvis jeg allerede kan se data  på  skærmen, burde jeg også kunne exportere, f.x. køn, forældres telefon etc Men - jeg behøver nok ikke at se adresse, opskrivningsdato etc

**Comment by lakridserne** [comment]
Det var på ingen måde en afvisning af din bug report - det var blot en note til når vi skal lave det :)

**Comment by mhewel** [comment]
det kunne jo ogås være at sådanne data kunne exporteres fra f.x. "deltagere" siden, som også lige nu viser en ting jeg lige havde glemt: Foto tilladelse (men har så ikke køn med)..
(jeg forstod det heller ikke som en afvisning, men en sund diskussion om at finde det rette der skal laves)

**Comment by Rotendahl** [comment]
@lakridserne vi kunne også flytte fototilladelse over til en person i stedet for at den er bundet på en aktivitet.

**Comment by lakridserne** [comment]
@Rotendahl Ja. Men det kan være man siger til nogle arrangementer - der må vi godt - og andre må vi ikke.

**Comment by Rotendahl** [comment]
Hvis man har den på personen så kan vi bare tage den med i aktivitets-tilmeldings formen. Så defaulter den til "Nej", men hvis man har ændret til "Ja" så defaulter den til det. 
Så har vi en fototilladelse per mand.

**Comment by lakridserne** [comment]
Ja, men det skal vel stadig kunne ændres pr. aktivitet

**Comment by Rotendahl** [comment]
Når vi skifter til den nye model så kan vi evt. have den på events, og person men ikke sæson.

**Comment by lakridserne** [comment]
Hvorfor ikke på sæson? Det er da også vigtigt at få tilladelse der.

**Comment by Rotendahl** [comment]
Tanken var at den på personen så gik til sæsonen. Men vi kan også bare have den på sæsonen. 
Så når man gik ind på sin person detaljer med alder, adresse osv. så kunne man også se den opplysing om en selv.

**Comment by lakridserne** [comment]
Jeps, det forstår jeg, men det er ligesom for at sikre os at have tilladelsen (GDPR er mere strikt omkring at have tilladelsen end før).

**Comment by mhewel** [comment]
PR748 burde dække dette, da der under Deltagere nu er muligt at udtrække mere detaljeret info om deltagere

**Comment by mhewel** [comment]
PR748 er i prod
