### ISSUE TITLE
[Feature] Udvid get_live_data

### ISSUE THREAD

**Issue by Rotendahl** [CodingPirates/forenings_medlemmer#479]
**Overordnet beskrivelse af funktionen**
For at gøre det nemmer at sætte review apps og lokal udvikling op, kan vi udvide vores `get_live_data` funktion så den også dumper emailTemplates og aktiviteter. 

**Ting der skal gøres:**
1. Udvid: https://github.com/CodingPirates/forenings_medlemmer/blob/master/members/management/commands/dump_public_data.py til at inkludere email_template og aktiviteter
2.  Opdater https://github.com/CodingPirates/forenings_medlemmer/blob/master/members/management/commands/get_live_data.py så den også loader det. 
3. Udvid test https://github.com/CodingPirates/forenings_medlemmer/blob/master/members/tests/test_dump_data.py

**Comment by nallic** [comment]
Jeg vil i stedet for forslå at templates rykkes til statiske filer i stedet for i databasen

**Comment by Rotendahl** [comment]
Den synes jeg også er en god ide! 
Den står også i vores backlog https://github.com/CodingPirates/forenings_medlemmer/projects/2#card-19005058
Det var bare som et hotfix indtil da.
