### ISSUE TITLE
[Feature] Lav aktiviteter offentlige. 

### ISSUE THREAD

**Issue by Rotendahl** [CodingPirates/forenings_medlemmer#483]
**Overordnet beskrivelse af funktionen**
Både oversigts siden over aktiviteter og siden for den enkelte aktivitet burde være offenligt. 
Så skal "Tilmeld" knapperne bare udskiftes med en "log ind" knap.

**Comment by JakobLibak** [comment]
Jeg foreslår at alle aktiviteter som udgangspunkt skal være synlige. Det vil sige både synlige for brugere der ikke er logget ind, men også aktiviteter som normalt er skjult for brugere fordi vi kun viser dem til inviterede brugere.

Ændringer:
1. `/activities` skal være synlig for brugere der ikke er logget ind
2. `/department_signup` skal være synlig for brugere der ikke er logget ind
3. Under `/activities` skal alle aktive arrangementer vises uanset om der er fri tilmelding eller ej. Aktiv = slutdato > dags dato
4. Aktiviteter under `/activities` skal have den sædvanlige grønne knap med [Tilmeld <navn> til aktivitet] for de personer, der må/kan tilmelde sig. Hvis det ikke er muligt at tilmelde nogen personer i familien skal der stå "_Denne aktivitet kræver invitation eller er kun åben for bestemte aldersgrupper. Tryk her (link) for at opskrive på venteliste til næste gang [Afdelingsnavn] opretter en ny aktivitet._". Link skal tage brugeren til `/department_signup`
5. Sektionen med _Tilmeldte arrangementer_ skal splittes i to sektioner med default _Igangværende_ og _Afsluttede_. Det gør det mere overskueligt for familier med flere børn og mange tidligere tilmeldinger. Koncept skal være lige som under `/department_signup`, hvor man kan vælge mellem at opskrive eller se opskrivninger.

**Comment by rasmusselsmark** [comment]
Er implementeret. Vi har på møde i udviklingsgruppen den 3. april derfor lukket dette issue
