### ISSUE TITLE
[Feature] Mulighed for tilmelding til PiratNyt når man melder sig til som frivillig

### ISSUE THREAD

**Issue by JondareHM** [CodingPirates/forenings_medlemmer#486]
Camilla har efterspurgt en eller anden form eller checkbox eller noget så folk som tilmelder sig som frivillige også kan vælge at blive tilmeldt PiratNyt når de alligvel er i gang.

User story:

Jens vil gerne være frivillig, så Jens går ind og melder sig til.
I tilmeldingsformen ser han så en checkbox for noget som hedder PiratNyt som ser meget spændende ud, så han klikker ja tak, og bliver tilføjet mailing listen.

Det burde være rimeligt nemt, da Mailchimp allerede har noget API eller noget til nemt at lave tilmeldingsforms, som man nok kan kigge på.

**Comment by lakridserne** [comment]
Det er bestemt en nice-to-have feature. Hvis man ligger det til sidst i et tilmeldingsflow kan vi nærmest bare smække en iframe ind at de tilbyder.

**Comment by Rotendahl** [comment]
Det er et del element af #482, men godt at have den som sin egen del issue.

**Comment by mhewel** [comment]
Møde 2023-05-01: Besluttede at lukke denne med reference til #787  der er implementeret
