### ISSUE TITLE
Lav union.members() funktionen

### ISSUE THREAD

**Issue by JakobLibak** [CodingPirates/forenings_medlemmer#487]
Funktionen union.members() er nødvendig for at kunne se hvem der er medlem af de enkelte foreninger.

#291 og #391 er afhængige af at den funktion eksisterer.

**Comment by JakobLibak** [comment]
Hej Kristoffer

Det vil være en stor hjælp, hvis du har mulighed for at gå videre med denne. Hvis du ikke har tid i nærmeste fremtid, så meld endelig tilbage, så vi kan prioritere andre kræfter anderledes.

Venlig hilsen
Jakob
@lakridserne

**Comment by mhewel** [comment]
Møde 2023-05-01: Besluttede at lukke denne med reference til #776
