### ISSUE TITLE
Opdatering af FAQ [Feature]

### ISSUE THREAD

**Issue by JakobLibak** [CodingPirates/forenings_medlemmer#502]
FAQ på https://codingpirates.dk/crmhjaelp/ trænger gevaldigt til en opdatering af alle tekster. Det er egentlig ikke en del af medlemsystemet, men det får sit eget kort her, så vi ikke glemmer det.

**Comment by mhewel** [comment]
se entry_page.html.
Istedet for crmhaelp så til https://codingpirates.dk/faq-medlemssystemet/

**Comment by mhewel** [comment]
crmhjaelp siden på wordpresss skal så ændres / fjernes (evt linke til FAQ siden)
