### ISSUE TITLE
Sortering i aktiviteter efter tid/dato som standard

### ISSUE THREAD

**Issue by MikeyAndersen** [CodingPirates/forenings_medlemmer#512]
**Overordnet beskrivelse af funktionen**
Aktiviteter i medlemssystemet er kun noget jeg kigger efter når jeg har en aktiv én der skal arbejdes med og selv hvis jeg skal gå tilbage så vil jeg hellere have en sortering baseret på hvor gammel aktiviteten er (på tværs af afdelinger) og vil gerne slippe for det ekstra tryk der er. :D

**User story**
(Eksempel på frivillig sign up)

1.  Mikey trykker ind på aktiviteter
2. Mikey ser at aktiviteterne er sorteret som standard efter tid/dato
3. Mikey slipper for et ekstra tryk

**Mock Ups**
Jeg ved godt det er en lille ting, men tænkte også det var hurtigt ordnet. Det er ikke et kritisk problem!

**Comment by JakobLibak** [comment]
Hej Mikey

Tak for at du tager dig tid til at skrive. Jeg er ikke helt sikker på at jeg forstår hvornår du har brug for et ekstra tryk. Hvis jeg går ind under aktiviteter med min profil, hvor jeg kan se på tværs af to afdelinger, så er den som standard sorteret efter dato. Vil du gerne have listen sorteret faldende i stedet for stigende? Eller misforstår jeg helt hvad du gerne vil have ændret?
![image](https://user-images.githubusercontent.com/31068308/79055045-192c9e00-7c4a-11ea-8828-1a52b57d6311.png)

Venlig hilsen
Jakob

**Comment by Scheel-Lonsdale** [comment]
Det er siden activities når man ser på det som forældre 🙂(se billede)
Den må meget gerne blive vist dato sorteret og dernæst efter navn 
Og endnu bedre var hvis man med tiden kunne tilføje dropdown filter så man ikke skulle scrolle så meget


![billede](https://user-images.githubusercontent.com/23579819/169892394-8bd1473b-99ec-4e48-a0ee-1a3107d0e5bd.png)

**Comment by mhewel** [comment]
Møde 2023-05-01: Der blev lavet PR #807 med sortering efter navn, flere kolonner, søgning, gruppering efter region etc..
Vi besluttede at lukke #512
