### ISSUE TITLE
Giv nye brugere mulighed for selv at angive et password [Feature]

### ISSUE THREAD

**Issue by JakobLibak** [CodingPirates/forenings_medlemmer#518]
Nye brugere kan ikke selv angive passwords, når de opretter sig.

**Comment by JondareHM** [comment]
Nogen preferancer for hvor og hvordan password felterne er og ser ud? Lige nu er det bare to felter nederst i signup formen, lige over knappen.

Derudover tænker jeg om vi skal sætte nogle validators på? Kan se Django har nogle ret så gode indbyggede vi bare kan bruge.

**Comment by Rotendahl** [comment]
Jeg lavede lidt med validators engang, men det nåede aldrig langt nok til at merges ind. 
Du kan nok få noget inspiration her https://github.com/Rotendahl/forenings_medlemmer/pull/13/files#

Særligt her https://github.com/Rotendahl/forenings_medlemmer/blob/f35397f27f879dd4d7c7f20b3969f660be68caa4/forenings_medlemmer/settings.py#L184-L191
