### ISSUE TITLE
[Feature] Archival of old events so they don't appear in filter dropdowns

### ISSUE THREAD

**Issue by JondareHM** [CodingPirates/forenings_medlemmer#549]
This is mostly for the superusers, but if you want to filter for example the person list based on the events people have participated in, there is a loooooooong list of events, most of which are years past and thus no longer relevant. 

Therefore it would be a huge help if either the list was just restricted to the last year or so of events, or if possible, you could choose what years worth of events to see.

**Comment by mhewel** [comment]
There are now filters on the person view to show:
Current year and future
Last year
Years before last year

@lakridserne & @rasmusselsmark : I'll suggest to mark this issue as solved. Agree ?

**Comment by rasmusselsmark** [comment]
Vi har nu f.eks. "(Aktive)" dropdown. Vi har på møde i udviklingsgruppen den 3. april derfor lukket dette issue
