### ISSUE TITLE
Pris på aktivitet skal være i kroner

### ISSUE THREAD

**Issue by DSDeniso** [CodingPirates/forenings_medlemmer#55]
<img width="379" alt="screen shot 2015-08-13 at 07 34 57" src="https://cloud.githubusercontent.com/assets/5363898/9243210/d2af8a9c-418d-11e5-8c58-9fc5131413f0.png">

**Comment by nallic** [comment]
Internt skal det være i øre. 
Men det ville være rart hvis admin interfacet udstillede i kroner (ligesom bruger siden selvfølgeligt gør det)

**Comment by DSDeniso** [comment]
Men hvorfor? Vi kommer vel kun til at have aktiviteter der koster hele kronor — og risikerer også fejl og aktiviteter der koster 199,95 :disappointed:

**Comment by nallic** [comment]
Systemet skal kunne håndtere ører. Der vil altid komme situationer, hvor man skal dele beløb, eller der f.eks. skal tages højde for 1.75% kort gebyr osv. Det er ikke smart at låse sig ude fra starten.

**Comment by DSDeniso** [comment]
Ændret til: Pris på aktivitet skal være i kroner, men tillade kommatal.

**Comment by johnrohde** [comment]
Tillad mig at være nørdet omkring området.

Flydende komma tal på computere er ekstremt farlige når man skal arbejde med penge. Jeg kan varmt anbefale at bruge heltal. 64 bit heltal er dejligt store så derfor giver det mening at køre det hele i ører.

Festen opstår typisk når man skal lave procent operationer. Dette medfører brøkdele af ører, som skal afrundes og resultaterne af disse afrundinger skal føres ind og ud af en afrundingskonto. Penge kan ikke bare køre ud og ind af et magisk IEEE 754 hul.

Denne viden er selvfølgelig ikke en jeg har fået på den lette måde ...

**Comment by DSDeniso** [comment]
Jeg genkender problematikken, men fra et usability synspunkt er det ikke optimalt at skulle indtaste ører.

Jeg "konverteringen" (aka. sletning af komma) bare sker inden dataen gemmes :smiley:

**Comment by goblinhero** [comment]
Fixed it - skal lige bruge lidt grundig testning :)

**Comment by nallic** [comment]
Lad os lige overveje at gøre dette her gennemført - Decimal på alle models, ikke kun activity. Det er ikke godt at have mixede typer rundt omkring.

**Comment by Rotendahl** [comment]
Fixed
