### ISSUE TITLE
[BUG] Afdelings siden på codingpirates.dk vises med medlemmer.codingpirates headeren

### ISSUE THREAD

**Issue by JondareHM** [CodingPirates/forenings_medlemmer#586]
Hvis man går ind på codingpirates.dk/afdelinger så bliver HELE medlemmer.codingpirates.dk/departments siden indlejret, komplet med header og det hele, hvor det kun er selve kortet og listen som skal være der.
![2020-08-10_13h43_41](https://user-images.githubusercontent.com/17178122/89883798-f5ae3b80-dbc8-11ea-8383-b49eddbeaf72.png)

Det er desværre ikke helt nemt at fixe, da meget af det CSS som siden bruger kommer fra base, og det er derfor ikke bare muligt at smide kortet og listen over i sin egen fil og kun indlejre den, da det i så fald vil se forkert ud, medmindre vi duplikerer en hel del af vores CSS.

Håber at der er en nemmere og mere elegant løsning en det.

**Comment by benj5378** [comment]
Fixed med #682

**Comment by benj5378** [comment]
Fixet i #682
