### ISSUE TITLE
Medlem og deltager bør adskilles

### ISSUE THREAD

**Issue by nallic** [CodingPirates/forenings_medlemmer#61]
lige nu, er modellen at man skal være medlem for at deltage i en aktivtet. Men i praktis er der deltagere, der ikke betaler og derfor ikke er medlemmer. Vi kan ligeså godt have en datamodel, der aspejler virkeligheden. .. dog kunne man lave atributter på "member" .. den er ret syltet ind i alting nu.

**Comment by nallic** [comment]
Definition af medlem:
Alle summer af payments over 75 i en given forening, giver et medlemskab. Payment peger på en aktivitet og denne aktivitets afdeling, bestemmer medlemsskab.

Man kan være medlem flere steder indenfor et år.

Vi fjerner "medlems" tabellen.

**Comment by lakridserne** [comment]
Vi har besluttet os for at bibeholde medlemstabellen. Ved køb af medlemsskab skal det specificeres hvad man betaler for (aktivitet, medlemsskab, evt. andre ting).
