### ISSUE TITLE
Der er vist en off by one bug: 29 tilmeldte på ITU, med en grænse på 30, fik tilmeldingen til at lukke (og skrive at 30 er tilmeldt)

### ISSUE THREAD

**Issue by nallic** [CodingPirates/forenings_medlemmer#62]

**Comment by goblinhero** [comment]
Den kan jeg ikke genskabe - vi bruger kun .seats_left() et sted - og der beregnes den korrekt. Jeg har prøvet at lave en aktivitet lokalt og tilmeldt børn til den var fyldt - alt virkede som forventet.
