### ISSUE TITLE
Påmind folk om nye afdelinger

### ISSUE THREAD

**Issue by nallic** [CodingPirates/forenings_medlemmer#64]
Send en email når nye afdelinger er tilgængelige.

**Comment by nallic** [comment]
Udnyt geo information - send samlet oversigt - evt. sammen med "opdater dine informationer"

**Comment by rasmusselsmark** [comment]
Vi har på udviklermøde den 3. april valgt at lukke. Sekretariatet eller andre kan trække relevante potentielle medlemmer ud, og sende mail
