### ISSUE TITLE
Ventelisteoprydning [Feature]

### ISSUE THREAD

**Issue by JakobLibak** [CodingPirates/forenings_medlemmer#644]
Gør det muligt for kaptajner og sekretariat at håndtere ventelister og lave oprydning i ventelister.

Issue skal gøres mere detaljeret før vi kan gå i gang.

**Comment by rasmusselsmark** [comment]
Der er nu `Ventelister` under admin med mulighed for at fjerne fra ventelister, implementeret i https://github.com/CodingPirates/forenings_medlemmer/pull/819. Lukker dette issue
