### ISSUE TITLE
[BUG] Datoformat i https://members.codingpirates.dk/volunteer

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#667]
**Beskriv fejlen overordnet**
PÅ siden https://members.codingpirates.dk/volunteer er der et felt med fødselsdato.
Teksten er: "Fødselsdato (dd-mm-åååå)*", men "hjælpe-teksten" i selve feltet er "mm/dd/yyyy"

**Genskab fejlen**
Disse trin førte til fejlen:

1.  Url: https://members.codingpirates.dk/volunteer
2.  kig på Fødselsdato feltet

**Hvad skulle der være sket**
sammenhæng mellem hjælpetekst og det aktuelle datoformat

**Screenshots**
Giv endelig dine screenshorts hvis det give mening

**Enheder:**

-   OS: windows 10
-   Browser: Chrome
-   desktop:

**Comment by JakobLibak** [comment]
Hej @mhewel 
Det ser fint ud hos mig. Oplever du stadig problemet?

![image](https://user-images.githubusercontent.com/31068308/120399050-937f1c80-c33b-11eb-9459-7d2c50e6adf4.png)

VH Jakob

**Comment by rasmusselsmark** [comment]
Har testet igen her (Mac og Windows). Ser korrekt ud, vi lukker

**Comment by rasmusselsmark** [comment]
@mhewel kan genskabe på Linux, formentligt særlige regional settings. Fjern hardcodet "(dd-mm-åååå)" tekst, da date-picker viser format
