### ISSUE TITLE
Gør det muligt at tilmelde person direkte fra en aktivitets egen side [Feature]

### ISSUE THREAD

**Issue by JakobLibak** [CodingPirates/forenings_medlemmer#668]
Under `activity_view_person` og `activity_view_family` skal det være muligt at tilmelde personer fra familien direkte i stedet for at de skal gøre det under `/activities`. Genbrug samme logik.

Det vil gøre det muligt at lave et link direkte til et arrangement, og derfra kan brugeren tilmelde familiemedlemmer.

**Comment by rasmusselsmark** [comment]
Dette blev implementeret som en del af #695
