### ISSUE TITLE
Frivillig tilmelding indeholder lukkede afdelinger i dropdown [BUG]

### ISSUE THREAD

**Issue by JakobLibak** [CodingPirates/forenings_medlemmer#670]
Dropdownliste over afdelinger indeholder lukkede afdelinger på siden `/volunteer`.

Lukkede afdelinger er markeret med dato i feltet `closed_dtm`, så vidt jeg husker.
![image](https://user-images.githubusercontent.com/31068308/119037023-c1667780-b9b1-11eb-853d-5a4c7d7ccab3.png)

**Comment by JakobLibak** [comment]
@jarl-dk , du må gerne hjælpe med denne som førsteprioritet. Jeg vender tilbage på dit andet spørgsmål snarest.

**Comment by jarl-dk** [comment]
ok
