### ISSUE TITLE
Fødselsdato bliver ikke vist, når man retter person [BUG]

### ISSUE THREAD

**Issue by JakobLibak** [CodingPirates/forenings_medlemmer#674]
Persons fødselsdato bliver ikke vist, når man retter (eller ser) detaljer på personen.

![image](https://user-images.githubusercontent.com/31068308/120027489-b6d06180-bff3-11eb-84f6-ef5261181bcd.png)

**Comment by falle1234** [comment]
#684 Skulle gerne have fixet denne.

**Comment by rasmusselsmark** [comment]
Vi har testet her til aften, det fungerer. Lukker issue
