### ISSUE TITLE
Medlemskab og Støttemedlemskab skal vise forening i stedet for afdeling i liste [Feature]

### ISSUE THREAD

**Issue by JakobLibak** [CodingPirates/forenings_medlemmer#677]
Tabeller under `/membership` og `/support_membership` skal vise Forening i stedet for Afdeling i de to tabeller på hver side.

![image](https://user-images.githubusercontent.com/31068308/120398562-c7a60d80-c33a-11eb-8f03-d1b70b155c2b.png)

**Comment by jarl-dk** [comment]
Hvis man viser foreningen i stedet for afdelingen, så kommer det ikke til at matche overskriften. Dermed bliver informationen misvisende. Det tænker jeg ikke I vil have.
En anden løsning kunne være at tilføje en kolonne mere og slå datoerne smallere fx. "1/1-2021" eller slå dem sammen "1/1-2021 -- 31/12-2021"

**Comment by jarl-dk** [comment]
Undskyld. Nej nu forstår jeg. De bliver selvfølgelig listet på deres egen side så de bliver ikke blandet. Så overskriften skal selvfølgelig også bare rettes.
