### ISSUE TITLE
Opdater settings.BASE_URL til ikke at indeholde / [BUG]

### ISSUE THREAD

**Issue by JakobLibak** [CodingPirates/forenings_medlemmer#678]
`settings.BASE_URL` variabel indeholder en `/` i slutningen, og det skaber problemer med visse links.
Forslag til bugfix er at lave variable korrekt uden trailing `/` og derefter løbe alle dele af koden igennem, hvor der bliver generet links på baggrund af den variabel.

Senest er det opdaget i email invitationer sendt ud fra medlemsystemet.

**Comment by jarl-dk** [comment]
BASE_URL bliver sat i miljøet. Det skal sikres at diverse miljøer ikke har trailing slash. Jeg har lavet et PR til at sikre at den ikke kan starte hvis BASE_URL er sat forkert.
