### ISSUE TITLE
PR 682 er gået tabt [Bug]

### ISSUE THREAD

**Issue by JakobLibak** [CodingPirates/forenings_medlemmer#685]
Det lader til at vi har mistet PR #682 undervejs. Headermenuen er igen synlig under `/departments`.

Vi skal derudover have fjernet footer menuen fra samme side mens vi alligevel er i gang.

**Comment by benj5378** [comment]
#682 er ikke mistet. Der er bare aldrig opsat nogen kode, der ændrer `skip_context` variablen?

**Comment by benj5378** [comment]
@JakobLibak Jeg prøvede at køre master lokalt, og der var ingen header. Kan det være fordi, at master ikke er sendt mod production?

**Comment by JakobLibak** [comment]
Den er klaret.
