### ISSUE TITLE
Kaptajner skal kunne se alle adresser [Feature]

### ISSUE THREAD

**Issue by JakobLibak** [CodingPirates/forenings_medlemmer#692]
En kaptajn kan kun se adresser der er tilknyttet sin afdeling og profil. De kan godt oprette nye adresser. Vi bør tilrette adgang, så kaptajnsprofilen kan se alle adresser.

**Comment by rasmusselsmark** [comment]
Implementeret i https://github.com/CodingPirates/forenings_medlemmer/pull/783, lukker dette issue (men vi opretter issue for at sikre privacy omkring adresser)
