### ISSUE TITLE
[FEATURE rettelse] - Betaling for sæsonaktivitet, ændres fra 75 kr til 100 kr (for betaling til CP DK)

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#702]
**Beskriv fejlen overordnet**
Er f.x. angivet under aktivitet med teksten "På prisen for aktiviteten fratrækker vi automatisk 75 kr per barn hvis det er en sæsonaktivitet

**Genskab fejlen**
Disse trin førte til fejlen:

**Hvad skulle der være sket**
Der skal stå 100 kr istedet for 75 kr

**Screenshots**

**Enheder:**

-   OS:
-   Browser:
-   Smartphone/desktop:

**Comment by falle1234** [comment]
#707 Skulle gerne have rettet denne.

**Comment by mhewel** [comment]
Er implementeret (og med i migrations #26 fra 20220425)
