### ISSUE TITLE
[BUG]Siden der viser detaljer om støttemedlemskab/foreningsmedlemskab skal ikke vise antal deltagere

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#718]
**Beskriv fejlen overordnet**
Disse 2 type aktiviteter har normalt et stort max-antal-deltagere, og der skal ikke vises tekst som:

**Pladser:**
9999 af 9999 pladser ledige.

**Genskab fejlen**
Log in som almindelig bruger, se på "MEdlemsskaber" eller "Støttemedlemskaber", og vælg en af dem fra listen.

**Comment by mhewel** [comment]
Snakkede m Kristoffer om at dette nok skal laves som et hack til nuværende datamodel. Ved ny datamodel (der er blevet diskuteret) kan det så være nemmere at løse denne..

**Comment by rasmusselsmark** [comment]
Dette er implementeret, men vi har på møde i dag oprettet https://github.com/CodingPirates/forenings_medlemmer/issues/875 for at forbedre
