### ISSUE TITLE
[Feature] Send forældre til Familie siden efter oprettelser af barn/værge/forældre

### ISSUE THREAD

**Issue by Scheel-Lonsdale** [CodingPirates/forenings_medlemmer#723]
**Send forældre til Familie siden efter oprettelser af barn/værge/forældre**
Ved at sende forældre direkte til familie siden kan de med det samme se, at det er lykkedes at oprette et familie medlem. Lige nu lander man på oversigten og tror man har trykket forkert og skal derefter til at finde familie siden for at se om familie medlemmet rent faktisk blev oprettet.

**Gennemgang**
(der skal oprettes et familie medlem)

1.  Maria(mor) går ind på familie siden
2.  Vælger opret barn/værge/forældre
3.  Udfylder felterne påkrævet og trykker OPRET
4.  Nu skulle hun gerne lande direkte tilbage til familie siden(se billede) og se at barn/værge/forældre blev oprettet

**Mock Ups**
![billede](https://user-images.githubusercontent.com/23579819/168466068-4029e9f9-0932-4a4a-a23f-18362f010df8.png)

**Comment by falle1234** [comment]
Så vidt jeg kan se, så bliver PersonCreate udelukkende kaldt fra /family/Person/TYPE
`url(r"^family/Person/(?P<membertype>[A-Z]{2})$", PersonCreate, name="person_add")`
Så vi bør kunne vidersende til "family_detail"-siden i alle tilfælde. 

Jeg laver gerne ændringen. Det tager 2 sekunder :)

**Comment by mhewel** [comment]
@falle1234  - det vil være dejligt - det er lige blevet bemærket igen at der er den fejl :-)
