### ISSUE TITLE
[BUG] Ret teksten på Tilmeld dit barn siden

### ISSUE THREAD

**Issue by Scheel-Lonsdale** [CodingPirates/forenings_medlemmer#726]
**Ret teksten på Tilmeld dit barn siden**
Når man går ind for at tilmelde sit barn, så der pt i teksten: Indtast barnets og forældrenes informationer, **for at tilmelde en Coding Pirates-workshop, eller for at komme med på ventelisten.** - Dette er misvisende da forældre tror det er nok blot at skrive sig selv og barnet op i medlemssystemet. 

**Fejl optræder**
Disse trin førte til fejlen:

1.  Forælder lander på Coding Pirates sitet ved tilmelding [Tilmeld dit barn]
2.  Klikker på -> Tilmeld dit barn (knappen)
3.  Lander nu på medlemssystemets oversigt 🤔
4.  Vælger så en af de 4 muligheder derinde og bliver først nu her guidet videre login siden, hvor der UNDER log in er tilmeld dit barn knappen
5. Trykker på -> Tilmeld barn (knappen)
6. Lander nu på opskrivningssiden for at skrive sit barn og i medlemssystemet(endelig)
7. Mødes at teksten i toppen: Indtast barnets og forældrenes informationer, **for at tilmelde en Coding Pirates-workshop, eller for at komme med på ventelisten.** - Dette er misvisende da forældre tror det er nok blot at skrive sig selv og barnet op i medlemssystemet. 
8. Udfylder og forlader siden, for tror jo at de også har tilmeldt barnet en workshop eller venteliste...

**Dette burde ske**
Man burde lande på siden for at skrive sit barn op(udfylde) med det samme, for mange klik og vi mister brugerne. Man skal pt klikke 3 gange for at nå den side, det er 2 for meget. Dertil burde teksten på siden hedde: **Indtast barnets og forældrenes informationer, for at blive opskrevet i medlemssystemet. Husk at når I har skrevet jer op, at logge ind i medlemssystemet og skrive barnet op på nærliggende afdelingers venteliste for senere at kunne modtage en invitation til en sæson.**

**Screenshots**
Her ses nuværende tekst på siden, der bør rettes
![billede](https://user-images.githubusercontent.com/23579819/169704789-43a5a9ee-8e13-472d-8750-1f86c413de22.png)

**Comment by Un10ck3d** [comment]
Den her skal lukkes
