### ISSUE TITLE
[BUG]Sortering efter navn under "Invitationer" virker ikke

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#735]
**Beskriv fejlen overordnet**
Sortering af Invitationer efter navn virker ikke

**Genskab fejlen**
I admin modulet, under "Invitationer". Vælg evt en aktivitet. Klik så på "Person" kolonne header - sortering virker ikke

1. Gå til https://members.codingpirates.dk/admin/members/activityinvite/
2. Klik på Person header

Forventet: Sorteret efter navn
Faktisk: Sortering er ikke efter navn

**Hvad skulle der være sket**
listen af personer skulle gerne være sorteret (som f.x. listen under "Personer" valgt i venstre side)

**Enheder:**

-   OS: Windows 10
-   Browser: Chrome
-   desktop:

**Comment by rasmusselsmark** [comment]
Genskabt i dag på udviklermøde. Sorterer måske på id?
