### ISSUE TITLE
[Feature]ADMIN: Afdeling/lokalforeningssiderne skal have liste af admins

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#736]
**Overordnet beskrivelse af funktionen**
Hvem kan administrere en lokalforening/afdeling - kan det blive vist i admin modules på forening/afdeling siderne

(Input fra frivilligemøde d 2022-08-09)

**Comment by rasmusselsmark** [comment]
Pt. er det ikke trivielt for Sekretariatet at tildele admin rettigheder for en lokalafdeling, kræver man går ind på hver enkelt medlem.

Forslaget er at man kan vælge og se en liste i stedet. @mhewel har nogle idéer 🙂
