### ISSUE TITLE
[Feature]Venteliste i ADMIN skal også vise tidspunkt for hvornår man skrev sig på givne venteliste

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#737]
**Overordnet beskrivelse af funktionen**
Input fra frivilligmøde d 2022-08-09: Det vil være dejligt at vise det tidspunkt hvor barnet er skrevet på en given venteliste (så kan man vælge at invitere efter det tidspunkt istedet for det tidspunkt barnet er skrevet op i systemet)

Det kan være det er nødvendigt at lave ny sektion i Admin modules: Venteliste, for at vise denne dato.

**Comment by rasmusselsmark** [comment]
PR #819 er merged 🎉

**Comment by rasmusselsmark** [comment]
Er implementeret. Lukker issue
