### ISSUE TITLE
[Feature] Automatisk venteliste oprydning

### ISSUE THREAD

**Issue by lakridserne** [CodingPirates/forenings_medlemmer#744]
## Oprydning af venteliste
Vi har snakket om at der skal være noget automatisk oprydning af venteliste ifht. forkerte aldersgrupper i første omgang.
Måske skal vi gå grovere til værks og smide alle af og sende emails, men det er en lidt farlig måde at gøre det på.

Vi snakkede om, om der skal være et filter til kun at vise dem der kan deltage i aktiviteter (7-17 år), som er tjekket pr. default.

Fjern alle der er ældre end 17 år, evt. med en automatisk mail med henvisning til at blive frivillig.

**Comment by mhewel** [comment]
Det er nu lavet mulighed for at admins kan slette fra ventelister..

**Comment by rasmusselsmark** [comment]
Vi besluttede at lukke, jvf tidligere kommentar
