### ISSUE TITLE
[BUG]Admin got too many rights

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#746]
Admin brugere har rettigheder til at give andre rettigheder end det er nødvendigt
Der skal ses på at reducere rettigheder for Admin, så de stadigvæk kan lave andre brugere (f.x. afdelings kaptajner)

**Comment by rasmusselsmark** [comment]
Ifølge @mhewel er denne implementeret indenfor de seneste par måneder som del af andet oprydningsarbejde
