### ISSUE TITLE
Export af CSV på deltagere kan ikke håndtere æ,ø,å.. 

### ISSUE THREAD

**Issue by nallic** [CodingPirates/forenings_medlemmer#76]
(rapporteret af Jari)

**Comment by goblinhero** [comment]
Den håndterer det fint - Jari skal holde op med ukritisk at putte ting i Excel :-)

Excel forventer ANSI/Western-1252 - vi eksporterer i UTF-8. Jeg synes det er en dårlig ide at lave det om af hensyn til dem, der ikke bruger windows
