### ISSUE TITLE
[Feature] Login husker hvor du var før login

### ISSUE THREAD

**Issue by lakridserne** [CodingPirates/forenings_medlemmer#762]
**Overordnet beskrivelse af funktionen**
Når du logger ind vil det være smart hvis den husker hvor du var før login.

**User story**
1.  Jørgen får link til aktivitet'
2. Jørgen vil gerne tilmelde sit barn.
3.  Jørgen klikker login og logger ind
4. Jørgen lander tilbage på samme aktivitet, i stedet for forsiden.

**Comment by rasmusselsmark** [comment]
Opgraderet til A, da vi har haft en nylig support request på dette flow (kan dog ikke finde tråd nu...)

Mikael post'ede https://forum.djangoproject.com/t/redirecting-user-to-page-after-login/14603/9

**Comment by rasmusselsmark** [comment]
Løst med https://github.com/CodingPirates/forenings_medlemmer/pull/968
