### ISSUE TITLE
[BUG]Medlem information under Person angiver forkerte data 

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#768]
**Beskriv fejlen overordnet**
Information om medlemsskab er forkert/mangelfuld - hvis personen har lavet noget i forskellige afdelinger.

**Genskab fejlen**
Log ind of find. f.x. person med id 5728 .
Denne person har deltaget i et hackathon i 2016 på DIKU,
Disse trin førte til fejlen:

Logget på Admin modul, fundet en person og er på siden for at redigere.
Scroller ned, og kigger på afsnittet med "MEDLEM".
Her angives en afdeling, som er den første afdeling denne person har deltaget i en aktivitet i (med Indmeldt dato som d. 1. i det år), og så udmeldt kan være 31.december i året med sidste aktivitet.

**Hvad skulle der være sket**
Medlemskab burde være oversigt over sæsonaktiviteter (der gør personen til medlem) og foreningsmedlemskaber.

**Screenshots**
https://members.codingpirates.dk/admin/members/person/5728/change
Scrolle ned til MEDLEM

**Enheder:**
Windows 10, Chrome 107

**Comment by lakridserne** [comment]
Denne skal ikke oprettes som en bug da den fungerer som designet. Den skal oprettes som en feature - eller epic hvor vi skal omskrive medlemstabellen. Det er lige før jeg tror der ligger tickets på det i forvejen.
