### ISSUE TITLE
[Feature]Venteliste håndtering

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#770]
**Overordnet beskrivelse af funktionen**
Information om personer på venteliste er ikke overskuelig, og det er ikke nemt at vedligeholde for en admin

Forslag til ændringer:
Item A: 
- Ny admin side for venteliste (nyt menu punkt i venstre side i Admin modulet): Liste af personer på venteliste, med filter på afdelinger. 
- Mulighed for at vælge en eller flere personer på venteliste og udfør "send email om at personen er fjernet fra venteliste grundet oprydning, ... barnet kunne være uden for aldersgruppen.. log ind og opskriv barnet på venteliste igen.. oprettelsesdato .. )
- Vælg personer og indbyd til aktivitet (som man kan under Personer)

Hermed er det muligt at få ryddet op i ventelister, med fornuftig information til familien, og de kan komme på igen (med deres oprindlige oprettelsesdato).

**Comment by lakridserne** [comment]
Vi bør diskutere om vi skal opfordre til at rydde op på denne måde da den er medvirkende til at vi har så mange der ikke er på venteliste og folk tror de står på den.
