### ISSUE TITLE
[BUG]Deltager-betalings-info viser Andet er aftalt hvis betaling skal foregå 1. januar

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#777]
**Beskriv fejlen overordnet**
når der er oprettet et arrangement "næste år", så skal betalingen foregå 1. januar (for at have betaling samme år som aktiviteten).
Lige nu vises der "Andet er aftalt", selvom der er en payment record (som ikke komme hvis man havde trykket på "andet er aftalt")

**Genskab fejlen**
Disse trin førte til fejlen:

1.  Loggede ind på admin
2.  Klik på Deltagere
3.  se deltagere for arrangement næste år (evt brug årstalsfilter i toppen)
4.  Der vises "andet er aftalt" for de fleste (nogle enkelte er afvist)

**Hvad skulle der være sket**
Der skulle havde været anden besked (f.x. "Betaling sat til 1. januar 2023")

**Screenshots**

**Enheder:**
-   OS: Windows
-   Browser: Chrome

**Comment by mhewel** [comment]
PR#778 er klar

**Comment by lakridserne** [comment]
Denne er fikset.
