### ISSUE TITLE
[BUG] Tidspunkt for oprettelse af betaling på deltagere er forskudt 1 time

### ISSUE THREAD

**Issue by lakridserne** [CodingPirates/forenings_medlemmer#781]
**Beskriv fejlen overordnet**
Hvis man ser på deltagere er den oprettelsestid der står på betalingen en time for tidligt.

**Comment by rasmus-unity** [comment]
Formoder vi gemmer tiden i UTC i database, hvilket i så fald er korrekt? Generelt kunne det være en god idé at se på hvordan vi formatterer dato/klokkeslæt per bruger, så f.eks. @mhewel kan vælge at få datoer vist som yyyy-mm-dd 🙂

**Comment by lakridserne** [comment]
Ja altså det er vel korrekt nok, handler mere om at det bør stå ens på tværs af platformen.

**Comment by mhewel** [comment]
Der er gennemført en betaling 2022-12-13.
Under payment står den som oprettet kl 10:01 og betalt kl 10:02
under Deltagere står betalingsinfo til aqt være 09:02 (og oprettet kl 09:01)
Jeg ser lige på det

**Comment by mhewel** [comment]
I databasen er 
added_at = 2022-12-13 09:01:42.317854+00
confirmed_at = 2022-12-13 09:02:35.003668+00

Nu er spørgsmålet jo -hvad er den rigtigt værdi..
Der står jo "+00" (som nok angiver det er UTC), men har vi garanteret at det UTC vi opretter de værdier med ?

**Comment by mhewel** [comment]
har lige oprettet en ny workshop, og members_activity.update_dtm (for den aktivitet) fik værdien 2022-12-26 10:06:57.664723+00 (og nu er min tid 11:06 UTC+1) så det ser jo ganske rigtigt ud som UTC tid der bliver sat ned..

**Comment by rasmusselsmark** [comment]
Vi kan lige se på det på torsdag når vi mødes, men umiddelbart ser det korrekt ud at vi gemmer UTC i databasen, og vi så skal vise lokal tid i UI

**Comment by mhewel** [comment]
jeg har fået det løst nu..
PR#782 er oprettet

**Comment by mhewel** [comment]
har lidt problemer med at bruge "pytz".. forsøgte at tilføje til package-lock.json, men vist uden held
