### ISSUE TITLE
Vis alder, postnummer og ventelisteplads under invitationer

### ISSUE THREAD

**Issue by JakobArkob** [CodingPirates/forenings_medlemmer#79]
Det ville være rart, hvis man kunne se alder, postnummer og ventelisteplads/tilmeldt under invitationerne. 

Jeg mister i hvert fald overblikket over aldersfordelingen, og om jeg prioriteret deres plads på ventelisten.

**Comment by StefanBols** [comment]
Alder og postnummer kan jeg forstå. Men ventelistepladsen giver ikke helt mening. Når der kun sendes invitationer ud til dem som der er plads til :blush:

**Comment by JakobArkob** [comment]
Vores afdeling er en del af Frederiksberg afdelingen, hvor der er en del på venteliste, desuden er der en del som aldrig giver svar på invitationen, så jeg har inviteret flere end, hvad der er plads til på holdet.
Vi er stadig ikke fyldt op endnu.
Jeg tror grunden til, at jeg forslår, at man kan se hvornår folk er tilmeldt under invitationen, hænger sammen med mit manglende overblik over systemet - hvis det giver mening.
Det vigtigste for mit vedkommende er, at alder og postnummer er synligt.

**Comment by StefanBols** [comment]
Jeg har oprettet et pull request med ændringerne. Jeg har ikke medtaget ventelistepladsen. Men alder og postnummer. Nu er det blot op til de høje herrer om ændringerne er godkendte :blush:

**Comment by JakobArkob** [comment]
Fedt godt arbejde!
Det er sgu så godt, at der er gode frivillige med IT-kompetencer i Coding Pirates - det er jo sjovt nok det Coding Pirates handler om. :)
Jeg har desværre ikke erfaringen med den slags programmering, så kan ikke hjælpe så meget andet end med forslag til ændringer.

**Comment by StefanBols** [comment]
Jeg har hellere ikke arbejdet med Django før, heller ikke Git. Men læste den her:
Https://docs.djangoproject.com/en/1.9/intro/tutorial01/
Og så prøvede jeg mig frem :blush:

**Comment by JakobArkob** [comment]
Jeg kan se det er skrevet i Python og det kan jeg faktisk lidt af. Det gør det i hvert fald nemmere at gå i gang med :)
Det bedste man kan er at prøve sig frem!

**Comment by nallic** [comment]
Jeg har manuelt stjålet din patch Stefan :)

**Comment by StefanBols** [comment]
@nallic du burde skamme dig - min første patch :sob:
