### ISSUE TITLE
[Refactor] Visning af køn som barn/voksen og mulighed for "Andet" køn

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#793]
**Hvad skal refactors og hvorfor?**
Der er flere forskellige steder i koden hvor vi ser på køn/gender på en person.
I databasen står der enten "MA" (Male) eller "FM" (Female), men skal "MA" nu vises som "Dreng" eller "Mand" og tilsvarende for "FM" - skal det vises som "Pige" eller "Kvinde"

Jeg vil foreslå en ændring til person.py, lave en ny function der laver denne håndtering, f.x.

```
def gender_text(self):
    if self.gender == "MA":
        if self.age_years() < 18:
            return "Dreng"
        else:
            return "Mand"
    elif self.gender == "FM":
        if self.age_years() < 18:
            return "Pige"
        else:
            return "Kvinde"
    else:
        return "Andet"

gender_text.admin_order_field = "-birthday"
gender.short_description = "Køn"
```

Søg efter: "MA" eller "FM" i den samlede kode og find de steder der skal ændres      

Test, test lidt mere test !

**Comment by mhewel** [comment]
og i den forbindelse er der i activityparticipant_admin, under def export_csv_full, en ny beregning af alder, men den er allerede lavet på person: person.age_years()

**Comment by lakridserne** [comment]
God ide. Kunne man forestille sig, at man lod være med at beregne alderen, men bruger det vi allerede har med om det er et barn eller voksen? Og så får lavet en procedure for at skifte det?

Man kunne også gøre det den anden vej rundt, men så er ulempen at det er sværere at bruge det i udtræk.

**Comment by mhewel** [comment]
man kunne godt se på membertype, jeg havde nu bare valgt 18 år som skille linje mellem brug af dreng/pige og mand/kvinde, da jeg synes det giver lidt mere mening

**Comment by mhewel** [comment]
og hvor kunne det være dejligt hvis de 20 personer der har birthday=NULL fik en fødselsdag.. evt via noget anonymisering (da jeg antager de ikke har deltaget i noget i mange mange år)

**Comment by lakridserne** [comment]
Problemet med det er ikke så meget om det giver mening - det gør det, men også lige så meget, at hvis vi skal bygge videre på systemet giver det nok bedre mening at vi standardiserer fremfor at der er implementeret en masse forskellige forretningsregler forskellige steder.

**Comment by lakridserne** [comment]
Altså med andre ord, hvis vi har 1 sted en regel er defineret, fremfor 5 steder, så skal vi også kun vedligeholde det ene sted.

**Comment by mhewel** [comment]
Det kunne måske være en ide at ændre dropdown for køn til at vise 2 værdier:
Dreng/Mand
Pige/Kvinde

**Comment by mhewel** [comment]
Målet med denne er også at der er et sted hvor reglen er, så vi nemmere kan bruge en læsbar værdi for køn. Lige nu er der igen og igen omskrivning fra "MA" til "dreng" osv.
Så kan vi altid ændre dette ene sted til at have en anderledes logic, hvad enten der skal stå "dreng", "mand", "dreng/mand", "ham" eller tilsvaende for "MA" og tilsvarende for "FM"

**Comment by lakridserne** [comment]
Og det er en god ide kun at have det 1 sted, men når vi har barn og forældre (som i min optik burde ændres til voksen) så synes jeg det ville give mening at bruge den værdi og selvfølgelig sørge for at håndtere den.

**Comment by mhewel** [comment]
Skal vi tilføje "OT" (Other) = Andet ?

**Comment by rasmusselsmark** [comment]
> Skal vi tilføje "OT" (Other) = Andet ?

Ja, per feedback fra online møde 26/2-2023:

```
Der er stadig ikke en mulighed for at inkludere andet køn end dreng og pige
Så en boks for: andet/ukendt/vil ikke oplyse
```

**Comment by mhewel** [comment]
Løst ved implementering af PR #803
