### ISSUE TITLE
Implementer sletning af familie medlem.

### ISSUE THREAD

**Issue by nallic** [CodingPirates/forenings_medlemmer#8]

**Comment by nallic** [comment]
Slet ikke rigtigt - men sæt en "deleted_dtm".
Når der er gået X dage forsvinder personen fra familie oversigt.

Opdater alle querys, der finder personer til ikke at inkludere slettede medlemmer

**Comment by nallic** [comment]
man kan lave en Person.objects_not_deleted query manager - det er nok den bedste løsning.

**Comment by nallic** [comment]
Vi sletter personer helt, hvis de ikke har tilknyttetede betalinger eller andre medlemskaber.
Sletning skal komme med en rimelig advarsel, hvor der bekræftes at man mister evt. ancienitet på ventelister.

Hvis personen har tilknyttet data, er det lidt uafklaret pt. hvordan vi sletter dem. Så indtil videre kan man ikke slettes i det tilfælde at man har betalinger eller tilmeldte arrangementer.

**Comment by rasmusselsmark** [comment]
Lukkes, da dette bliver en del af GDPR anonymiserings funktionalitet #739
