### ISSUE TITLE
Send invitationen igen, hvis man ændre i aktiviteten

### ISSUE THREAD

**Issue by JakobArkob** [CodingPirates/forenings_medlemmer#80]
Ja, det er for sådan en som mig, når jeg glemmer basale ting i invitationen. Det ville være en fantastisk feature, hvis jeg havde mulighed for at lave en lille rettelse i aktiviteten, hvor så invitationen vil blive gensendt til dem der allerede har fået en invitation.

Måske med en henvisning til rettelsen - dette er nok ikke så vigtigt, men noget man kan overveje.

**Comment by StefanBols** [comment]
Lige for at forstå dig korrekt. I tilfælde af at du har glemt at tilføje noget i invitationen eller lavet fejl. Så vil du have man skal kunne rette det - og at invitationen så sendes ud på ny :blush: ?

**Comment by JakobArkob** [comment]
Jeg har formuleret min oprindelige post lidt bedre nu. Kan godt se det var lidt uklart hvad jeg mente :)

Og det er helt rigtigt forstået - da jeg laver fejl og gerne vil opdatere invitationen, ville det være rart at det skete automatisk.

**Comment by nallic** [comment]
Invitationer indeholder ikke så meget af den tekst man skriver. Så hvis man retter beskrivelsen giver det ikke meget mening den genudsendes.

"
Hej {{person.name}}!

Du er blevet inviteret til vores kommende aktivitet: "{{activity.name}}" på {{activity.department.name}}. 

For at komme med, skal dine forældre gå ind på medlemssiden:
{{site}}{%url 'family_detail' family.unique  %}

På medlemssiden, kan I se pris, sted og tidspunkt og endeligt bekræfte og betale.

Men skynd jer ! - vi lukker flere flere ind fra ventelisten hver dag, så derfor er det vigtigt, hvis I vil med, at I melder jer til så hurtigt som muligt. Tilmeldingen lukker, når holdet er fyldt ud.

Hvis I alligevel ikke er interesserede, så kan I direkte sige nej tak på dette link:
{{site}}{%url 'invitation_decline' family.unique activity_invite.id %}

Så kan andre på ventelisten få jeres plads!

Med venlig hilsen Coding Pirates

"

**Comment by JakobArkob** [comment]
Ja det kan jeg godt se. Det er en smule forvirrende når man ikke er helt klar over, hvad folk ser.
Hvor ser folk aktiviteten? 
Jeg fik nemlig nogle spørgsmål angående vores workshops, som jeg troede man kunne se gennem invitationen, men det er nok det som forvirrer mig?

Jeg mangler også at få lavet hjemmesiden og det gik ret stærkt med at invitere folk.

**Comment by nallic** [comment]
linket i emailen linker til en side, hvor alt informationen er på. F.eks. https://members.codingpirates.dk/activity/10/

**Comment by JakobArkob** [comment]
Ah ok. Tak. Men hvad sker der hvis der så bliver ændret i aktiviteten?

**Comment by JakobArkob** [comment]
Og tak for opklaringen. Jeg bliver meget bedre til systemet :)

**Comment by nallic** [comment]
Vi glæder os til pull-requests ! :)

**Comment by JakobArkob** [comment]
Ja det kan jeg godt forstå! :)
