### ISSUE TITLE
[BUG] Fjern forening fra aktivitetsredigering

### ISSUE THREAD

**Issue by lakridserne** [CodingPirates/forenings_medlemmer#801]
## Beskriv fejlen overordnet
Hvis du redigerer aktiviteten har du nu mulighed for at redigere hvilken forening den pågælende aktivitet er på. Jeg kan godt se hvorfor det er blevet lavet sådan, men jeg synes vi skal fjerne det. Det er yderst sjældent, at du har behov for at ændre det, og det er temmelig meget et hack.

Hvis der er problemer med det kan en admin rette i det. Men nr. 1 må være at vi ikke har behov for det felt fordi vi løser det med medlemsksaber på anden vis.

Jeg tror det er @mhewel der har implementeret muligheden for at redigere hvilken forening den aktivitet specifikt hører under.

**Comment by mhewel** [comment]
Korrekt - jeg havde lavet foreningsmedlemsskab manuelt for en forening, og kunne se at union var sat til 1 (CP DK), så jeg valgte at lave den synlig.

Så længe vi har det felt under aktivitet (og det bruges kun til foreningsmedlemskab/støttemedlemskab) bør det helt klart være der.

**Forslag :** 
ændring i activity_admin.py
fra:
'''
            "Forening",
            {
                "description": "<p><b>Bemærk:</b> Denne værdi bruges kun til foreningsmedlemsskab/støttemedlemsskab.</p>",
                "fields": ("union",),
            },
'''
til:
'''
            "Forening",
            {
                "classes": ("collapse",),
                "description": "<p><b>Bemærk:</b> Denne værdi bruges kun til foreningsmedlemsskab/støttemedlemsskab.</p>",
                "fields": ("union",),
            },
'''
så vises det som
![image](https://user-images.githubusercontent.com/58829786/210496900-85d04584-5931-426e-b69d-d6f10cca165a.png)

**Comment by mhewel** [comment]
eller istedet for skjul, så noget a'la beskrevet her
https://rocity.github.io/2021-12-01-Django-Admin-Conditional-Fieldsets/
Men ved check om det er foreningsmedlemskab/støttemedlemsskab
Det bedste ville nu være at slippe for at ha union med i activity

**Comment by lakridserne** [comment]
Det er et hack der blev lavet for hurtigt at understøtte det. Det bør ikke være i interfacet, da det ikke er noget man ved noget om hvad skal bruges til, medmindre man kender systemet ret godt. For de fleste kaptajner vil det jo se skørt ud, at foreningen står til Coding Pirates Denmark på de fleste aktiviteter.

**Comment by lakridserne** [comment]
Vi er helt enige om at det felt skal udfases. Det bliver det også. Men selvom det er i modellen lige nu bør det ikke være noget du kan rette i.

Alternativt laver jeg det så du kun kan se og rette det som superadmin.

**Comment by mhewel** [comment]
ok - det var en god ide m superadmin er de eneste der kan se/rette i det..
det må jo så holde os til ilden mht at få udfaset det felt
