### ISSUE TITLE
[BUG] Script til at oprette foreningsmedlemsskabsaktiviteter medtager lukkede afdelinger

### ISSUE THREAD

**Issue by lakridserne** [CodingPirates/forenings_medlemmer#806]
## Beskriv fejlen overordnet

Når vi kører scriptet, som genererer foreningsmedlemsskabsaktiviteterne bliver lukkede afdelinger medtaget i listen over afdelinger under foreningen.

## Genskab fejlen
Tjek en forening med lukkede afdelinger.

## Hvad skulle der være sket
Lukkede afdelinger skal ikke vises. Hvis der ikke er nogen åbne afdelinger under foreningen, skal aktiviteten ikke genereres.

**Comment by mhewel** [comment]
Note: SEK har opdateret foreninger/afdelinger her i slut februar 2023, så lukkedato er opdateret..

**Comment by rasmusselsmark** [comment]
Formentligt fører #776 til at dette script ikke er nødvendigt fremover
