### ISSUE TITLE
[BUG] CSV filer med danske tegn importeres ikke korrekt i Excel

### ISSUE THREAD

**Issue by rasmusselsmark** [CodingPirates/forenings_medlemmer#809]
## Beskriv fejlen overordnet

Demonstreret af Michael Hansen og Mikael Hewel til "kaptajndag" den 26. januar 2023. Hvis man eksporterer liste fra f.eks. https://members.codingpirates.dk/admin/members/person/ som indeholder danske tegn, bliver disse ikke importeret korrekt i Excel på Windows.

## Genskab fejlen

Disse trin førte til fejlen:

1. Gå til f.eks. https://members.codingpirates.dk/admin/members/activityparticipant/
2. Vælg en eller flere personer med danske tegn i navn
3. Vælg `CSV Export` fra dropdown og tryk på `Udfør` knappen
4. Åbn filen i Excel

Filen åbnes i Excel, men danske tegn vises ikke korrekt

## Hvad skulle der være sket

Danske tegn skulle vises korrekt

## Enheder

- OS: Windows med Microsoft Excel
- Browser: Chrome
- Smartphone/desktop: Desktop

**Comment by rasmusselsmark** [comment]
Har en fornemmelse af at det måske handler om hvilken encoding der bruges (bare et gæt)

**Comment by mhewel** [comment]
https://hilton.org.uk/blog/csv-excel

**Comment by rasmusselsmark** [comment]
Ifølge Michael Hansen er problemet der stadig, han har sendt følgende skærmbillede:
![image](https://user-images.githubusercontent.com/3763552/216812156-04e00c6f-967b-45b6-8749-87fcf0a9befb.png)

Genåbner issue

**Comment by mhewel** [comment]
er det export under Deltager eller under Personer.. Denne ændring var vist kun for export under Deltager

**Comment by mhewel** [comment]
Udfra skærmbilledet er det den fra Personer..

**Comment by rasmusselsmark** [comment]
Opdatering fra Michael:
> Jeps, Deltagere virker, men Personer virker ikke.
