### ISSUE TITLE
[BUG]Aldersgrænse ved invitationer beregnes udfra barnets alder ved udsendelse af invitation, ikke barnets alder ved aktivitetsstart/-slut

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#834]
## Beskriv fejlen overordnet
Har lige sendt invitationer ud, og en dreng der lige nu er 9, men fylder 10 inden start d. 23. februar kunne kun inviteres til aktivitet der var for 7-10 år, men ikke for aktivitet for 10-17 år

**Comment by mhewel** [comment]
person_admin.py:
                                        and (
                                            activity.max_age
                                            >= current_person.age_years()
                                            >= activity.min_age
                                        )

**Comment by lakridserne** [comment]
Dette er ikke en bug, men en ændring vil jeg mene.

Man kan diskutere om vi skal ændre det.

Det der taler for, at vi ændrer det er, at vi på den måde får børn der er den alder når aktiviteten starter.

Det der taler imod er:
- Det kan være forvirrende at man har sat alderen til mindst 10 år, og en 9-årig så bliver inviteret og generere bug reports
- Der er som regel kort tid mellem invitation og aktivitetsstart. Dermed er det en begrænset forskel.

**Comment by mhewel** [comment]
Hvis en ændring som denne kan medføre andre / nye fejl, så skal de selvfølgelig også rettes.
Vi skal vel nok lave en ny metode der kan checke en person imod en aktivitet, mht fødselsdato, start/slut dato og aldersgrænse.

**Comment by lakridserne** [comment]
Jeg taler ikke om fejl i koden. Jeg taler om, at det for kaptajnerne vil se ud som om der er fejl i systemet hvis vi laver det her om fordi man så pludselig ser en 9-årig komme med på, selvom aktiviteten kun er fra 10 år.

**Comment by rasmusselsmark** [comment]
Del af #872

**Comment by mhewel** [comment]
#872 er implementeret
