### ISSUE TITLE
[Feature]Admin - Deltagere: Sortering af afdelinger i Afdelingsfilter : Brug navnet istedet for zip

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#837]
## Overordnet beskrivelse af funktionen
Når man ser på Afdelings filteret under Deltagere, så er det ikke nemt at se hvad der bliver sorteret efter. Er det zip ?
Sorter listen efter navn.
Check evt også sortering på de andre filtre

**Comment by rasmusselsmark** [comment]
Afventer #894
