### ISSUE TITLE
[Feature]Admin > Aktiviter: Alle foreninger og afdelinger vises i filtre

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#838]
## Overordnet beskrivelse af funktionen
Filtrene for Foreninger og Afdelinge viser alle værdier, selv dem men ikke kan se aktivitet for.
Heldigvis bliver der ikke vist aktiviteter man ikke har adgang til (så hvis man vælger f.x. en afdeling man ikke burde have adgang til, så vises der ingenting).
Det er en mindre kosmetisk rettelse, a'la PR #836 for Invitationer

**Comment by rasmusselsmark** [comment]
Afventer løsning i #851

**Comment by mhewel** [comment]
Implementering af #851 hjalp, så issue kan hermed blive lukket
