### ISSUE TITLE
[BUG]: Man kan ikke lave den samme email to gange

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#844]
## Beskriv fejlen overordnet
ifm at lave mulighed for sletning fra ventelister, opdagede jeg at hvis jeg havde en person P1 på venteliste til afdeling AF1, og valgte at fjerne P1 fra ventelisten for AF1, så blev der sendt email som forventet.
Men hvis P1 så valgte at opskrive sig til AF1 igen, og admin senere valgte igen at fjerne P1 fra AF1, så blev der ikke lavet ny email.
Har lige forsøgt tilsvarende scenarie med invitation: Inviter P1 til aktivitet AK1 (i afdeling AF1) - der blev sendt email.
Valgte så at fjerne invitationen, og prøve igen, og også her blev der ikke lavet email 2. gang.

**Comment by lakridserne** [comment]
Altså det er jo en feature at vi sikrer at man ikke modtager samme email flere gange - det kunne hurtigt blive irriterende. Men det er klart at vi må lave nogle undtagelser ved specifikke mails.

**Comment by mhewel** [comment]
Hvis man nu er blevet fjernet fra venteliste en gang, og så der er oprydning igen, så får man ikke nogen email denne gang.. :-(

**Comment by mhewel** [comment]
forslag : ændre makeEmail (i emailtemplate.py):
fra:
    def makeEmail(self, recievers, context):
til:
    def makeEmail(self, recievers, context, force_email = false):
    
hvor force_email er en boolean
og så ændre:
fra:
       if (
                members.models.emailitem.EmailItem.objects.filter(
                    person=person,
                    reciever=destination_address,
                    activity=activity,
                    template=self,
                    department=department,
                ).count()
                < 1
            ):
  til
         if (
                members.models.emailitem.EmailItem.objects.filter(
                    person=person,
                    reciever=destination_address,
                    activity=activity,
                    template=self,
                    department=department,
                ).count()
                < 1
             or force_eamil):
  
Så er det default som vi kender det nu, og har man så en situation som fx. ved fjerne fra ventelisten, kan man i koden kalde makeEmail med extra argument: true

**Comment by lakridserne** [comment]
Forslag:

Skift `force` ud med `allow_multiple`

**Comment by mhewel** [comment]
Denne blev lukket ifm ændring der koom i drift i sidste weekend, og afprøvet ifm emails for "slet fra invitationer" der kom i drift d. 27. february
