### ISSUE TITLE
[Feature] Når man har tilmeldt sig aktivitet, skal man ikke sendes tilbage til venteliste opskrivning

### ISSUE THREAD

**Issue by rasmusselsmark** [CodingPirates/forenings_medlemmer#846]
## Overordnet beskrivelse af funktionen

Tilbagemelding fra online møde 26/2-2023:

> Folk sendes tilbage hvor man startede(venteliste, arrangement, event, medlemskab) det gør at de skriver sig på ventelisten igen med det samme efter tilmelding
> 
> **Svar:** Det skal der kigges på! Så man lander på siden med der viser man har tilmeldt sig/betalt(tilmeldte aktiviteter/medlemsskaber)

## User story

1. Barn er opskrevet på venteliste til afdeling
1. Modtager invitation og tilmelder sig

Sørg for at når man har tilmeldt sig, er det tydelig for brugeren (typisk en forældre), at det ikke er nødvendigt at skrive sig på venteliste igen

**Comment by mhewel** [comment]
man kan evt fjerne knappen for tilmelding til venteliste for den givne afdeling (og evt skrive at "person-navn" går til en aktivitet lige nu)..

**Comment by mhewel** [comment]
@rasmusselsmark : Jeg har lige lavet en test (lavet et arrangement med fri tilmelding, pris 0 kr). Tilmeldt og "betalt" for et barn. 
Derefter kommer jeg til siden for dette arrangement, hvor jeg kan se at barnet er tilmeldt og knap for at tilmeld andet barn.
Er det OK ?
