### ISSUE TITLE
[Feature] En aktivitet skal kunne placeres i den rette region og ikke være bundet af adressen for CP Afdelingen

### ISSUE THREAD

**Issue by Scheel-Lonsdale** [CodingPirates/forenings_medlemmer#867]
Med den nye opdatering, hvor alle lister er sorteret/opdelt efter regioner, mangler der en måde en vise CPDK og andre aktiviteter der afholdes af en forening/afdeling, men ikke nødvendigvis afholdes i den region afdelingen kommer fra.

Med et punkt for **Regioner** med dropdown, som skal vælges ift lokationen på aktiviteten, når man udfylder aktiviteten, så vil den figurere under regioner relevante for brugerne der skal tilmelde sig aktiviteten.

Jeg bor i Københavns området, og jeg vil gerne tilmelde mig BIK 2023 i Lyngby, men fordi det er et CPDK event, så figurer eventet under Region Syddanmark, hvor CPDK foreningen har lokation henne. 

Eksempel: Jørgen fra Ballerup vil gerne tilmelde sit barn til BIK 2023

1. Jørgen logger ind i systemet 
2. Han går til siden Aktiviteter og ser nu default den relevante region ud fra hans adresse
3. Han leder nu efter BIK 2023 på listen og finder den ikke
4. Jørgen bruger søgefunktionen og leder efter BIK 2023, men den søger under Regions fanen og Jørgen ved ikke at CPDK der afholder eventet har lokation i Odense og at eventet derfor figurer under Regionen Syddanmark 
5. Jørgen sender nu mail til Sekretariatet om at han ikke kan finde eventet eller giver op

Billede af nuværende situation
![billede](https://user-images.githubusercontent.com/23579819/226312705-308b9684-2058-4eba-901d-733f1c054fd4.png)

**Comment by lakridserne** [comment]
Jeg anbefaler ikke, at løse det på den måde, men at tilføje adresse som objekt, som vi snakkede om. Det er den bedste måde rent strukturmæssigt.

**Comment by rasmusselsmark** [comment]
Relateret til #874

**Comment by mhewel** [comment]
Vi har arrangementer der ikke er knyttet til en bestemt region, f.x. Landsmøde, GameJam, SummerCamp etc.
det er typisk et fåtal der er aktive .. skal de være listet i hver region eller evt over regionslisterne ?

**Comment by mhewel** [comment]
relateret til #368

**Comment by mhewel** [comment]
For "fælles" ting (på tværs af regioner), såsom gamejam bik, landsmøde etc, regionskoden "Danmark" er blevet forslået af SEK (på møde dd.)
