### ISSUE TITLE
Mulighed for eksport af data

### ISSUE THREAD

**Issue by jenrik** [CodingPirates/forenings_medlemmer#87]
Det ville være smart hvis man kan trække data ud i csv og/eller json format, så man blandt andet kan lave deltager lister man kan printe og krydes om børne kommer til møderne.

**Comment by lakridserne** [comment]
Du kan allerede trække data ud i CSV. Gå til Personer og marker dem du vil eksportere. Herefter i top-menuen kan du vælge eksporter som csv.
