### ISSUE TITLE
[Feature]Link i aktivitetsbeskrivelse

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#873]
## Overordnet beskrivelse af funktionen
Ønske om at kunne angive en URL i en aktivitetsbeskrivelse, og når så den almindelige bruger ser på aktiviteten, er der et link man kan klikke sig videre på (f.x. til et spørgeskema el.lign)

**Comment by lakridserne** [comment]
Burde det være en WYSIWYG editor?

Dog skal man huske på at det ikke er alle der læser den beskrivelse.
