### ISSUE TITLE
[Feature]Automatisk tilføjelse af SEK admins til (nye) afdelinger/foreninger

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#879]
## Overordnet beskrivelse af funktionen
Ønske fra SEK:
_En del af de nye foreninger bliver vi ikke automatisk admins på, os der bør have adgang til alle. Frederikshavn eksempelvis._

**Comment by mhewel** [comment]
Note: Lige nu er det på den enkelte Admin at man angiver om vedkommende er admin for en afdeling/forening.
Tilsvarende burde være synligt under Afdeling/Forening, at hvis man har rettighederne for at håndtere brugere (dvs admins), så kan man her under afdeling/forening også tilfjøje/fjerne personer.
Det gør det jo nemt at se hvem der er admin for en afdeling/forening, og når man laver en ny afdeling/forening, er det nemt at tilføje personer (fra SEK f.x.)

**Comment by rasmusselsmark** [comment]
Implementeres i `save()` metoden, der gemmer pågældende objekt

**Comment by mhewel** [comment]
se også #980
