### ISSUE TITLE
[Feature]Betalingsinfo (under Admin > Deltagere) skal også indeholde betalt beløb

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#886]
## Overordnet beskrivelse af funktionen
I øjeblikket indeholder Betalingsinfo f.x. flg:
Betalt:2023-05-05 16:09. (Oprettet:2023-05-05 16:09)

Der ønskes også infom om det beløb der er betalt, f.x. formatteret sådan her:

Betalt: 250.00 kr. 2023-05-05 16:09. (Oprettet:2023-05-05 16:09)

**Comment by lakridserne** [comment]
Bemærk, at det nok er bedre at implementere når vi laver betalingsmodellen om.
