### ISSUE TITLE
[Feature]Skal man kunne disable "Venteliste" for en afdeling ?

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#888]
## Overordnet beskrivelse af funktionen
Der er afdelinger der ikke bruger ventelister, så kunne man evt under members.codingpirates.dk > Afdelinger vise noget info istedet for "Opskriv" knappen ?

**Comment by rasmusselsmark** [comment]
Ifølge @lakridserne har der været funktionalitet om afdelingen har venteliste, men dette ser ikke ud til at eksistere længere. Find den tidligere logik og genskab muligheden. Alt andet burde virke omkring direkte tilmelding til aktiviteter osv

F.eks. Sorø har efterspurgt dette for nyligt

**Comment by mhewel** [comment]
department.has_waiting_list blev fjernet i https://github.com/CodingPirates/forenings_medlemmer/pull/361

**Comment by mhewel** [comment]
https://members.codingpirates.dk/activities/#aktiviteter : 
Hvis en afdeling har disabled has_waiting_list, så skal der ikke være opskriv knapper for hver person, men en tekst med "Afdelingen bruger ikke venteliste"

https://members.codingpirates.dk/department_signup : Hvis en afdeling har disabled has_waiting_list, så skal der ikke være opskriv knapper for hver person, men en tekst med "Afdelingen bruger ikke venteliste" eller lign og link til ovenstående side
