### ISSUE TITLE
[BUG]: View-only admins virker ikke helt korrekt

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#891]
## Beskriv fejlen overordnet
Har lavet en ny gruppe der hedder "Revision", med en del "view" permissions.
Det er for revisor, hvor der ikke er mulighed for at ændre data.
MEN - ved test i prod, er der nogle fejl:
1. Klik på en afdeling, så er der fejl 500
1. Klik på en forening, så kan man redigere denne forening (og i admin menu er der et "+ Tilføj" ud for Foreninger)

Der skal lige laves mere test for at se om der er andre fejl

**Comment by rasmusselsmark** [comment]
Ikke vigtig lige nu, men bliver et problem i slutningen af året når revisorer skal tilgå systemet
