### ISSUE TITLE
[Feature]Admin/Foreninger: Exporter CSV liste af foreninger

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#893]
## Overordnet beskrivelse af funktionen
Efter ønske fra Sekretariatet, som bruger unødig lang tid på at få disse informationer. Exporter en CSV liste af de foreninger der er valgt  med:

- navn, adresse etc
- formand (navn, email, tlf)
- næstformand (navn, email, tlf)
- kasserer (navn, email, tlf)

**Comment by rasmusselsmark** [comment]
Afventer #897
