### ISSUE TITLE
[Feature] Inviter til diskussion om wiki

### ISSUE THREAD

**Issue by lakridserne** [CodingPirates/forenings_medlemmer#902]
## Overordnet beskrivelse af funktionen

Vi bør have en diskussion om at lave en wiki til FAQ mm.

**Comment by rasmusselsmark** [comment]
F.eks. udskift maskinrummet med en wiki, hvis der er interesse. Går som sådan udover decideret medlemssystem, men vil være brugbart

**Comment by rasmusselsmark** [comment]
Alternativt bruger vi bare Github og Github Pages 🙂

**Comment by mhewel** [comment]
Wiki.codingpirates.dk lever..
