### ISSUE TITLE
[Feature] Overblik over betalingsinfo under selve aktivitetens info

### ISSUE THREAD

**Issue by Scheel-Lonsdale** [CodingPirates/forenings_medlemmer#908]
Betalingsinfo på deltagerne, når man kigger på listen af deltagere under selve aktiviteten

Det ville være en hjælp for admins at de kan se om de tilmeldte deltagere på aktiviteten har betalt eller ej, når man går ind på selve aktiviteten.

Lige nu kan man kun se betalingsinfo på deltagerne når man går ind på deltagere.

Forslag til tilføjelse under selve aktiviteterne:
1. Admin går ind på aktiviteter
2. Finder den ønskede aktivitet og trykker på navnet
3. Kan se alle deltagere tilmeldt aktiviteten i bunden(se billede)
4. Må gerne også kunne se betalingsinfoerne herinde ud for deltager navnene

![billede](https://github.com/CodingPirates/forenings_medlemmer/assets/23579819/ef301e8f-751a-4ad5-b24c-d96b5a2c79f4)

**Comment by mhewel** [comment]
Jeg vil foreslå at vise "besked til arrangør" og "foto tilladelse" også, f.x. som dette:
![Screenshot_20230621_103308](https://github.com/CodingPirates/forenings_medlemmer/assets/58829786/5e93987b-4de8-4f79-89da-1891b84babc3)

**Comment by mhewel** [comment]
@Scheel-Lonsdale  - er ovenstående eksempel OK ?
