### ISSUE TITLE
[BUG]Admin > Deltagere: Afdelings filter viser alle afdelinger

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#951]
## Beskriv fejlen overordnet
Drop down med afdelinger skal kun vise de afdelinger man har adgang til

En beskrivelse af fejlen

## Genskab fejlen

Disse trin førte til fejlen:

1. Loggede ind '...'
2. Clicked på '...'
3. ...
4. Siden fejlede med fejlkode '...'

## Hvad skulle der være sket

Hvad prøvede du på

## Screenshots

Giv endelig dine screenshorts hvis det give mening

## Enheder

- OS:
- Browser:
- Smartphone/desktop:

**Comment by rasmusselsmark** [comment]
PR: https://github.com/CodingPirates/forenings_medlemmer/pull/954
