### ISSUE TITLE
[BUG]Aktivitet : Det må ikke være muligt at have tilmeldingsfrist efter arrangement er afsluttet

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#953]
## Beskriv fejlen overordnet
F.x. er der foreningsmedlemskab for en afdeling for 2022 (2022-01-01  til 2022-12-13), hvor tilmeldingsfristen er i 2030.

## Genskab fejlen

Disse trin førte til fejlen:

1. Loggede ind '...'
2. Clicked på '...'
3. ...
4. Siden fejlede med fejlkode '...'

## Hvad skulle der være sket

Hvad prøvede du på

## Screenshots

Giv endelig dine screenshorts hvis det give mening

## Enheder

- OS:
- Browser:
- Smartphone/desktop:

**Comment by mhewel** [comment]
Se også #943

**Comment by mhewel** [comment]
Fra møde m SEK idag fandt vi at der for et par dage siden var sendt invitationer ud, hvor invitations gyldighed var dagen før den var sendt ud..

**Comment by mhewel** [comment]
ifm udsendelse af invitationer er der forskellige checks, f.x. om man er gammel nok, for gammel, allerede deltager, er inviteret etc.
Det kunne måske være en ide at ændre dette en smule, så man kan invitere igen, hvis tidligere invitation er udløbet

**Comment by lakridserne** [comment]
> ifm udsendelse af invitationer er der forskellige checks, f.x. om man er gammel nok, for gammel, allerede deltager, er inviteret etc. Det kunne måske være en ide at ændre dette en smule, så man kan invitere igen, hvis tidligere invitation er udløbet, og vise dette som yderligere statistik

Så du mener at man ikke bare skal gøre det mere tydeligt at forlænge invitationen, evt. med mulighed for en email notifikation om at den er blevet forlænget?
