### ISSUE TITLE
[BUG] Kan ikke invitere personer der er gamle nok

### ISSUE THREAD

**Issue by lakridserne** [CodingPirates/forenings_medlemmer#975]
## Beskriv fejlen overordnet
Hvis jeg har en aktivitet, hvor jeg efter startdatoen inviterer nogen, som på startdatoen ikke er gammel nok, kan jeg ikke få lov til at invitere dem, fordi de ikke er gamle nok.

Jeg forventer, at hvis det er efter startdatoen, så skal den tage fødselsdatoen pr. dags dato.

**Comment by rasmusselsmark** [comment]
Revert PR: https://github.com/CodingPirates/forenings_medlemmer/pull/997 - genåbner dette issue
