### ISSUE TITLE
[Feature]Man bør først være deltager når der er betalt

### ISSUE THREAD

**Issue by mhewel** [CodingPirates/forenings_medlemmer#976]
## Overordnet beskrivelse af funktionen
Som i de fleste andre web-shops, så skal der betales først.

se også #848  og #97

**Comment by lakridserne** [comment]
Jeg mener at det er korrekt at den opretter en som deltager, men der skal selvfølgelig være en klar markering, og håndtering af det. Man kan så diskutere om det skal være synligt eller ej (personligt synes jeg det bør være synligt, eller det bør være noget jeg kan slå til at der skal være synligt for mig).

**Comment by lakridserne** [comment]
Lukker, og fortsætter i #848 og #97 .
