### ISSUE TITLE
Ændre "betal" knappen til "tilmeldings frist" overskrevet. 

### ISSUE THREAD

**Issue by Rotendahl** [CodingPirates/forenings_medlemmer#98]
Problem er at man ikke kan betale hvis fristen er overskredet.

**Comment by nallic** [comment]
Man skal altid kunne betale - hvis man blev tilmeldt.

**Comment by Rotendahl** [comment]
Man er ikke tilmeldt endnu, dette issue løses egentligt med VIP invitationer som også løser #67

**Comment by rasmusselsmark** [comment]
Vi tillader os på møde i udvikergruppen den 3. april 2023 at lukke denne. Kombination af at vi ikke ser den have høj nok prioritet i forhold til tid krævet
