### ISSUE TITLE
[Feature] Vend om, så andet er aftalt er angivet af kaptajnen

### ISSUE THREAD

**Issue by lakridserne** [CodingPirates/forenings_medlemmer#983]
## Overordnet beskrivelse af funktionen

I dag kan du vælge "Andet er aftalt" i stedet for at betale med kort / MobilePay - så bliver der ikke oprettet nogen betaling. Der er nogen der bruger det, men vores fornemmelse er, at de fleste ved en fejl får valgt det.

Derfor vil vi gerne vende det om, sådan at det er kaptajnerne der vælger det. I samme omgang introducerer vi også at man kan invitere en person til en speciel pris hvis man ønsker det. Vi tænker, at invitationsflowet skal være næsten det samme som i dag, undtagen at du kan vælge tingene til fra flowet også.

Hvis du efterfølgende vil rette i det, tilføjer vi, at du kan gå ind og redigere i invitationen, og ændre på pris, om man kan springe betalingen over, og udløbsdato på invitationen.

**Comment by mhewel** [comment]
Ser ud til at den er lavet i PR #1002 - der er implementeret.

**Comment by rasmusselsmark** [comment]
Er implementeret ifølge @lakridserne
